'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3620
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.ServiceUsers.Enquiry

    Partial Public Class SdsContributions

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblWarning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWarning As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cpContributionSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cpContributionSummary As Global.Target.Library.Web.Controls.CollapsiblePanel

        '''<summary>
        '''sdsContributionSummary1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sdsContributionSummary1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''cpActiveContributionLevels control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cpActiveContributionLevels As Global.Target.Library.Web.Controls.CollapsiblePanel

        '''<summary>
        '''serviceUserContributionLevel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents serviceUserContributionLevel1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''cpPendingContributionLevels control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cpPendingContributionLevels As Global.Target.Library.Web.Controls.CollapsiblePanel

        '''<summary>
        '''pendingServiceUserContributionLevel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pendingServiceUserContributionLevel1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''cpFinancialAssessments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cpFinancialAssessments As Global.Target.Library.Web.Controls.CollapsiblePanel

        '''<summary>
        '''financialAssessmentSelector1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents financialAssessmentSelector1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''cpHistoricNotificationLetters control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cpHistoricNotificationLetters As Global.Target.Library.Web.Controls.CollapsiblePanel

        '''<summary>
        '''historicNotificationLetters1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents historicNotificationLetters1 As Global.System.Web.UI.UserControl
    End Class
End Namespace
