'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.Res

    Partial Public Class ViewServiceUser

        '''<summary>
        '''TabStrip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TabStrip As Global.AjaxControlToolkit.TabContainer

        '''<summary>
        '''TabPanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TabPanel1 As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''lblReference control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReference As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboTitle As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''txtFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFirstName As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtSurname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSurname As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''cboGender control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboGender As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''txtNINo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNINo As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtDateOfBirth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDateOfBirth As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtDateOfDeath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDateOfDeath As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtCareManagerName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCareManagerName As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtCareManagerPhone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCareManagerPhone As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtCareManagerFax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCareManagerFax As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''TabPanel2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TabPanel2 As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''divResCare control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divResCare As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
