'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.Security

    Partial Public Class Login

        '''<summary>
        '''litPageOverview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPageOverview As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litLoginError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litLoginError As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblTimeout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTimeout As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmail As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPassword As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''lnkForgottenPassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkForgottenPassword As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''btnLogin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLogin As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''dvLicenceWarning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvLicenceWarning As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''dvLicenceError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvLicenceError As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
