'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1378
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class PageAsEmail

    '''<summary>
    '''litHtmlTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litHtmlTitle As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''aspnetForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents aspnetForm As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lnkHeaderLogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkHeaderLogo As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''MPPageTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPPageTitle As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''lnkCannotView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCannotView As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''MPPageOverview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPPageOverview As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''MPContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MPContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
