'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1378
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.SUNotif

    Partial Public Class ViewSUNotif

        '''<summary>
        '''btnViewScanned control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnViewScanned As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''divNotif control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divNotif As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
