'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.InPlaceSelectors

    Partial Public Class DebtorInvoices

        '''<summary>
        '''selector control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents selector As Global.Target.Abacus.Web.Apps.UserControls.DebtorInvoiceSelector
    End Class
End Namespace
