'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.InPlaceSelectors

	Partial Public Class InPlaceDomContractSelector

		'''<summary>
		'''txtNumber control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtNumber As Global.System.Web.UI.HtmlControls.HtmlInputText

		'''<summary>
		'''txtTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtTitle As Global.System.Web.UI.HtmlControls.HtmlInputText

		'''<summary>
		'''btnFind control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents btnFind As Global.System.Web.UI.HtmlControls.HtmlInputButton

		'''<summary>
		'''hidID control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents hidID As Global.System.Web.UI.HtmlControls.HtmlInputText

		'''<summary>
		'''valRequired control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator
	End Class
End Namespace
