'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.Admin.AnnualParameters

    Partial Public Class NonResidentialParameters

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''stdButtons1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents stdButtons1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''fsAllDomciciliaryParams control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsAllDomciciliaryParams As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''fsDomParamControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsDomParamControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtDetailsFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDetailsFromDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtDetailsToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDetailsToDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtDetailsMinCharge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDetailsMinCharge As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtDetailsMaxCharge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDetailsMaxCharge As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''fsWhenAssessingClientControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsWhenAssessingClientControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''cbAssessingClientAutoCalculateIsAllowance control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbAssessingClientAutoCalculateIsAllowance As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''fsWhenCalculatingWeeklyChargeControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsWhenCalculatingWeeklyChargeControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''cbCalculatingWcDoNotApplyMinCharge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbCalculatingWcDoNotApplyMinCharge As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cbCalculatingWcCapUnitCostOfServiceAtProvCharge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbCalculatingWcCapUnitCostOfServiceAtProvCharge As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''fsAssessableIncome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsAssessableIncome As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtAssessableMig18to24 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAssessableMig18to24 As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtAssessablePercentAssessableIncome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAssessablePercentAssessableIncome As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtAssessablePensionerCouple control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAssessablePensionerCouple As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtAssessableDreAllowance control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAssessableDreAllowance As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtAssessableMig25to59 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAssessableMig25to59 As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtAssessableDisabledCouple control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAssessableDisabledCouple As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtAssessableDreAllowanceCouple control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAssessableDreAllowanceCouple As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtAssessableMig60Up control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAssessableMig60Up As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtAssessableDreUpperLimit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAssessableDreUpperLimit As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''fsCapitalAllowanceControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsCapitalAllowanceControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''fsCapitalAllowanceDetailControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsCapitalAllowanceDetailControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtCapAllowancesDisgregardSingle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCapAllowancesDisgregardSingle As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtCapAllowancesDisgregardCouple control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCapAllowancesDisgregardCouple As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtCapAllowancesUpperLimitSingle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCapAllowancesUpperLimitSingle As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtCapAllowancesUpperLimitCouple control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCapAllowancesUpperLimitCouple As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''fsCapitalAllowanceCalculationControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsCapitalAllowanceCalculationControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtCapAllowancesCalculationWeeklyIncome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCapAllowancesCalculationWeeklyIncome As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtCapAllowancesCalculationPerPart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCapAllowancesCalculationPerPart As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtCapAllowancesCalculationInterestRate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCapAllowancesCalculationInterestRate As Global.Target.Library.Web.Controls.TextBoxEx
    End Class
End Namespace
