'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.Admin.AnnualParameters

    Partial Public Class NonResidentialIsAllowanceRates

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''stdButtons1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents stdButtons1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''fsAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsAll As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''fsDetailControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsDetailControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''cboType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboType As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''txtFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFromDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtToDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtFromAge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFromAge As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtToAge control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtToAge As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''fsAllowanceControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsAllowanceControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtAllowanceSingle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAllowanceSingle As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtAllowanceCouple control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAllowanceCouple As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtAllowanceHalfCouple control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAllowanceHalfCouple As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''fsDWPMIGRates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsDWPMIGRates As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtDWPMIGAllowanceSingle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDWPMIGAllowanceSingle As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtDWPMIGAllowanceCouple control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDWPMIGAllowanceCouple As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtDWPMIGAllowanceHalfCouple control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDWPMIGAllowanceHalfCouple As Global.Target.Library.Web.Controls.TextBoxEx
    End Class
End Namespace
