'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.Dom.SvcOrders

    Partial Public Class ServiceOrderFunding

        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''InfoLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents InfoLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblfundingError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblfundingError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''fundingRevisionDropDown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fundingRevisionDropDown As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''cbofundingEffectiveDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbofundingEffectiveDate As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''hid_ButtonClicked control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hid_ButtonClicked As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''hidFundingDSOID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidFundingDSOID As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''hidRevisionID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidRevisionID As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''ServiceOrderFundingContainer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ServiceOrderFundingContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''fundingRevisionDatePicker control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fundingRevisionDatePicker As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''fundingEffectiveDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fundingEffectiveDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''fundingClientGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fundingClientGroup As Global.System.Web.UI.UserControl

        '''<summary>
        '''Label4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''fundingClientSubGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fundingClientSubGroup As Global.System.Web.UI.UserControl

        '''<summary>
        '''Label2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''fundingTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fundingTeam As Global.System.Web.UI.UserControl

        '''<summary>
        '''Label3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''fundingCareManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fundingCareManager As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkUserGenerated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUserGenerated As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''lblUserGenerated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUserGenerated As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''fldFunding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fldFunding As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''svcTypeMenuContainer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents svcTypeMenuContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plannedSTList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plannedSTList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''otherSTList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents otherSTList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''UpdatePanel2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''optApportion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optApportion As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optCallOff control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optCallOff As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''phFinanceCodes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phFinanceCodes As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''fldButtons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fldButtons As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''btnFundingNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnFundingNew As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnFundingSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnFundingSave As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnFundingEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnFundingEdit As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnFundingDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnFundingDelete As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnFundingCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnFundingCancel As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
