'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.ServiceUsers.SpendPlans

    Partial Public Class Edit

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblWarning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWarning As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''stdButtons1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents stdButtons1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblReconsideredCosts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReconsideredCosts As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''imgReconsiderWarningText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgReconsiderWarningText As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''tabStrip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabStrip As Global.AjaxControlToolkit.TabContainer

        '''<summary>
        '''tabPlan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabPlan As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''client control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents client As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtReference control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReference As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''dteDateFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteDateFrom As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''dteDateTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteDateTo As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''lblEndReason control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEndReason As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''optAwaitingApproval control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optAwaitingApproval As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''optApproved control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optApproved As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''optCancelled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optCancelled As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''dteStatusDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteStatusDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''tabFinancial control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabFinancial As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''txtFinanceCode1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFinanceCode1 As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtFinanceCode2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFinanceCode2 As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''careManager control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents careManager As Global.System.Web.UI.UserControl

        '''<summary>
        '''team control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents team As Global.System.Web.UI.UserControl

        '''<summary>
        '''clientGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents clientGroup As Global.System.Web.UI.UserControl

        '''<summary>
        '''tabDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabDetails As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''phDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phDetails As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''btnAddDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddDetail As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''lblDetailsSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDetailsSummary As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDetailsSummaryDateFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDetailsSummaryDateFrom As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDetailsSummaryTotalCost control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDetailsSummaryTotalCost As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDetailSummaryIndicativeBudget control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDetailSummaryIndicativeBudget As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''tabCosts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabCosts As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''rptCosts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptCosts As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''tabDocuments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabDocuments As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''docSelector control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents docSelector As Global.System.Web.UI.UserControl

        '''<summary>
        '''tabNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabNotes As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''notesdiv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents notesdiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Notes1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Notes1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''btnTerminate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnTerminate As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''btnReconsiderCosts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnReconsiderCosts As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''hidSelectedTabIndex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidSelectedTabIndex As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidSelectedTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidSelectedTab As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidSpendPlanDateFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidSpendPlanDateFrom As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidSpendPlanDateTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidSpendPlanDateTo As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidDefaultBudgetPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidDefaultBudgetPeriod As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    End Class
End Namespace
