'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.Jobs.UserControls

    Partial Public Class AccrualsInterfaceStepInputs

        '''<summary>
        '''dteAccrualDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteAccrualDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''cboFinancialYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboFinancialYear As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''cboPeriodNum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboPeriodNum As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''txtFilePath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFilePath As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''hidCreatingJob control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidCreatingJob As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    End Class
End Namespace
