'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.Jobs.UserControls

    Partial Public Class PublishDebtorInvoicesStepInputs

        '''<summary>
        '''fsDebtorInvoices control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsDebtorInvoices As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''optInvoiceUnprinted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optInvoiceUnprinted As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''lblBillingType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBillingType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboBillingType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboBillingType As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''optInvoiceSingle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optInvoiceSingle As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''invoicePicker control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents invoicePicker As Global.System.Web.UI.UserControl

        '''<summary>
        '''fsDDPaymentDates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsDDPaymentDates As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtDDNonRes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDDNonRes As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtDDRes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDDRes As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''lblWarning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWarning As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''fsTransStatements control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsTransStatements As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''chkProduceStatements control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkProduceStatements As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''dteTransFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteTransFrom As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''dteTransTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteTransTo As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''valTransFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valTransFrom As Global.System.Web.UI.WebControls.RangeValidator

        '''<summary>
        '''valTransTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valTransTo As Global.System.Web.UI.WebControls.RangeValidator

        '''<summary>
        '''lblUsage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblUsage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtStatementFooter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStatementFooter As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''chkReplaceText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkReplaceText As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''fsSort control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsSort As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''cboSort control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboSort As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''hidCurrInvoice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidCurrInvoice As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidInvoiceChoice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidInvoiceChoice As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidProduceStatements control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidProduceStatements As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidReplaceText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidReplaceText As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    End Class
End Namespace
