'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.Jobs.UserControls

    Partial Public Class RecalcDomProviderInvoiceStepInputs

        '''<summary>
        '''lblProvider control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProvider As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''provider control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents provider As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblContract control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContract As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''domContract control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents domContract As Global.System.Web.UI.UserControl

        '''<summary>
        '''dteDateFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteDateFrom As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''dteDateTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteDateTo As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''chkCreateProforma control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCreateProforma As Global.Target.Library.Web.Controls.CheckBoxEx
    End Class
End Namespace
