'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3623
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.Jobs.UserControls

    Partial Public Class ucPaymentPreviewOptions

        '''<summary>
        '''optReportOnly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optReportOnly As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optGeneratePayments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optGeneratePayments As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''CustomValidatorPaymentPreviewOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CustomValidatorPaymentPreviewOptions As Global.System.Web.UI.WebControls.CustomValidator

        '''<summary>
        '''hidGenerateMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidGenerateMode As Global.System.Web.UI.WebControls.HiddenField
    End Class
End Namespace
