'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1378
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps

    Partial Public Class OccupancyEnq

        '''<summary>
        '''lblProperty control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProperty As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblService control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblService As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grpRegDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grpRegDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtDateFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDateFrom As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtDateTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDateTo As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''chkActive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkActive As Global.Target.Library.Web.Controls.CheckBoxEx

        '''<summary>
        '''chkProvisional control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkProvisional As Global.Target.Library.Web.Controls.CheckBoxEx

        '''<summary>
        '''chkSuspended control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSuspended As Global.Target.Library.Web.Controls.CheckBoxEx

        '''<summary>
        '''chkCancelled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCancelled As Global.Target.Library.Web.Controls.CheckBoxEx

        '''<summary>
        '''chkDocumentary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDocumentary As Global.Target.Library.Web.Controls.CheckBoxEx
    End Class
End Namespace
