'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1378
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps

    Partial Public Class ViewProvider

        '''<summary>
        '''btnEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnEdit As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''btnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''lblAmendReq control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAmendReq As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TabStrip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TabStrip As Global.AjaxControlToolkit.TabContainer

        '''<summary>
        '''TabPanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TabPanel1 As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''litReference control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litReference As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtLocalProviderID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLocalProviderID As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''litName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtWebsite control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtWebsite As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''litOrgType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litOrgType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''litCreditorsRef control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCreditorsRef As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''litVATExempt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litVATExempt As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''litVATNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litVATNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dteYearEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteYearEndDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''litProviderType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litProviderType As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litAccreditationExempt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litAccreditationExempt As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TabPanel2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TabPanel2 As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''TabPanel3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TabPanel3 As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''TabPanel4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TabPanel4 As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''TabPanel5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TabPanel5 As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''litBMESpecific control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litBMESpecific As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''litEthnicOrigins control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litEthnicOrigins As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litCulturalGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litCulturalGroup As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''TabPanel6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TabPanel6 As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''Repeater1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Repeater1 As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''valSum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valSum As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''btnSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
