'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.CreditorPayments.Batches

    Partial Public Class ucCreditorPaymentBatchCriteria

        '''<summary>
        '''lblCreatedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreatedDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCreatedDateValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreatedDateValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCreatedBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreatedBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCreatedByValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreatedByValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPaymentCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPaymentCount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPaymentCountValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPaymentCountValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPaymentValueNet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPaymentValueNet As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPaymentValueNetValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPaymentValueNetValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPaymentValueVAT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPaymentValueVAT As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPaymentValueVATValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPaymentValueVATValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPaymentValueGross control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPaymentValueGross As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPaymentValueGrossValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPaymentValueGrossValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPostingDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPostingDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPostingDateValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPostingDateValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPostingYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPostingYear As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPostingYearValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPostingYearValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPeriodNum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPeriodNum As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPeriodNumValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPeriodNumValue As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
