'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.EmailSender.Admin

    Partial Public Class DefaultPage

        '''<summary>
        '''lblDisabledWarning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDisabledWarning As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''litPollInterval control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPollInterval As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litBatchLimit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litBatchLimit As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litRetryLimit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litRetryLimit As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''litSentMessages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litSentMessages As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lblActionError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblActionError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rptStatusCounts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptStatusCounts As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
