'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.Security.Admin

    Partial Public Class UserEdit

        '''<summary>
        '''litPageError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPageError As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''stdButtons1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents stdButtons1 As Global.Target.Web.Library.UserControls.StdButtons

        '''<summary>
        '''cpe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cpe As Global.AjaxControlToolkit.CollapsiblePanelExtender

        '''<summary>
        '''pnlReports control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlReports As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lstReports control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstReports As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''divPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divPermissions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ctlPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlPermissions As Global.Target.Web.UserControls.ReportsButton

        '''<summary>
        '''TabStrip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TabStrip As Global.AjaxControlToolkit.TabContainer

        '''<summary>
        '''tabDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabDetails As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''txtFirstName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFirstName As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtSurname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSurname As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmail As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtStatus As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''pnlChangeStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlChangeStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''btnChangePassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnChangePassword As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnActive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnActive As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnSuspended control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSuspended As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnLocked control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnLocked As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnReactivate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnReactivate As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''tabRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabRoles As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''dlRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dlRoles As Global.Target.Library.Web.Controls.DualList

        '''<summary>
        '''tabInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabInfo As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''txtCreateDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCreateDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtLastLoginDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastLoginDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtLastLoginUserAgent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastLoginUserAgent As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtLastLoginIPAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastLoginIPAddress As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtPasswordDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPasswordDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtLastFailedLoginDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLastFailedLoginDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtRejectedLogins control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRejectedLogins As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''tabAdministrativeArea control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabAdministrativeArea As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''dlAdministrativeAreas control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dlAdministrativeAreas As Global.Target.Library.Web.Controls.DualList
    End Class
End Namespace
