'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3607
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.UserControls

    Partial Public Class CareTypeSelector

        '''<summary>
        '''divRes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divRes As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''optRes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optRes As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''divNonRes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divNonRes As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''optNonRes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optNonRes As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''divDP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divDP As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''optDP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optDP As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton
    End Class
End Namespace
