'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.UserControls

    Partial Public Class DomServiceOrderReports

        '''<summary>
        '''lstReports control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstReports As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''divDsoList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divDsoList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ctlDsoList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlDsoList As Global.System.Web.UI.UserControl

        '''<summary>
        '''divDsoDetailList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divDsoDetailList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ctlDsoDetailList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlDsoDetailList As Global.System.Web.UI.UserControl

        '''<summary>
        '''divDsoVisitList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divDsoVisitList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ctlDsoVisitList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlDsoVisitList As Global.System.Web.UI.UserControl

        '''<summary>
        '''divUnpaidDsoList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divUnpaidDsoList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ctlUnpaidDsoList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlUnpaidDsoList As Global.System.Web.UI.UserControl
    End Class
End Namespace
