'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.UserControls

    Partial Public Class NotesSelector

        '''<summary>
        '''divError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divError As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''Notes_Content control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Notes_Content As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''filterControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents filterControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''Notes_btnList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Notes_btnList As Global.System.Web.UI.UserControl

        '''<summary>
        '''Notes_btnEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Notes_btnEdit As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''Notes_btnView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Notes_btnView As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''Notes_btnNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Notes_btnNew As Global.System.Web.UI.HtmlControls.HtmlInputButton
    End Class
End Namespace
