'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3623
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.UserControls

    Partial Public Class PaymentToleranceControl

        '''<summary>
        '''lblRateCategoryDescriptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRateCategoryDescriptions As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''fsUnitsOfServiceControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsUnitsOfServiceControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''pnlVisitBasedUnitsofService control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlVisitBasedUnitsofService As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtAcceptableAdditionalUnits control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAcceptableAdditionalUnits As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtAcceptableAdditionalUnitsAsPercentage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAcceptableAdditionalUnitsAsPercentage As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtUnitsOfServiceCappedAt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUnitsOfServiceCappedAt As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''pnlUserEnteredUnitsofService control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlUserEnteredUnitsofService As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''chkSuspendInvoiceWhenPlannedUnitsExceeded control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSuspendInvoiceWhenPlannedUnitsExceeded As Global.Target.Library.Web.Controls.CheckBoxEx

        '''<summary>
        '''cboPaymentToleranceCombinationMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboPaymentToleranceCombinationMethod As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''fsCostOfServiceControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsCostOfServiceControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''pnlCostOfService control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCostOfService As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtAcceptableAdditionalPayment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAcceptableAdditionalPayment As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtAcceptableAdditionalPaymentAsPercentage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAcceptableAdditionalPaymentAsPercentage As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtCostOfServiceCappedAt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCostOfServiceCappedAt As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''divWarning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divWarning As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblWarning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWarning As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''hidPaymentToleranceID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidPaymentToleranceID As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hidPaymentToleraceGroupSystemType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidPaymentToleraceGroupSystemType As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hidPaymentToleranceDisplayMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidPaymentToleranceDisplayMode As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hidIsPaymentTolerancesSet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidIsPaymentTolerancesSet As Global.System.Web.UI.WebControls.HiddenField
    End Class
End Namespace
