'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3625
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.UserControls

    Partial Public Class PendingSuclChangesSelector

        '''<summary>
        '''PendingSuclChangesSelector_Error control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PendingSuclChangesSelector_Error As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''btnPreview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPreview As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnNotify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNotify As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
