'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.UserControls

    Partial Public Class ServiceOrderSelector

        '''<summary>
        '''ServiceOrderSelector_btnNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ServiceOrderSelector_btnNew As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''ServiceOrderSelector_btnCopy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ServiceOrderSelector_btnCopy As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''ServiceOrderSelector_btnCopy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ServiceOrderSelector_btnView As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''cTypeSelector control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cTypeSelector As Global.System.Web.UI.UserControl
    End Class
End Namespace
