'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.Dom.ProviderInvoices

    Partial Public Class BatchReports

        '''<summary>
        '''lblCreatedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreatedDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCreatedBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreatedBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvoiceCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvoiceCount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvoiceValueNet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvoiceValueNet As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvoiceValueVAT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvoiceValueVAT As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvoiceValueGross control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvoiceValueGross As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPostingDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPostingDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPostingYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPostingYear As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPeriodNum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPeriodNum As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lstReports control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstReports As Global.System.Web.UI.WebControls.ListBox

        '''<summary>
        '''divBatchSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divBatchSummary As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ctlBatchSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlBatchSummary As Global.System.Web.UI.UserControl

        '''<summary>
        '''divDpiList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divDpiList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ctlDpiList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlDpiList As Global.System.Web.UI.UserControl

        '''<summary>
        '''divDpiLineList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divDpiLineList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ctlDpiLineList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlDpiLineList As Global.System.Web.UI.UserControl

        '''<summary>
        '''divFirstPaymentDsoList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divFirstPaymentDsoList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ctlFirstPaymentDsoList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlFirstPaymentDsoList As Global.System.Web.UI.UserControl
    End Class
End Namespace
