'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.Dom.ProviderInvoices

    Partial Public Class PrintBatchContract

        '''<summary>
        '''lblCreatedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreatedDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCreatedBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreatedBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvoiceCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvoiceCount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvoiceValueNet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvoiceValueNet As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvoiceValueVAT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvoiceValueVAT As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvoiceValueGross control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvoiceValueGross As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilter As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFilters control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilters As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rptContracts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptContracts As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
