'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.Dom.ProviderInvoices

    Partial Public Class PrintInvoice

        '''<summary>
        '''lblFilterProvider control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilterProvider As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFilterContract control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilterContract As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFilterClient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilterClient As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFilterInvoiceNum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilterInvoiceNum As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFilterInvoiceRef control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilterInvoiceRef As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFilterWEDates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilterWEDates As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFilterStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilterStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFilterStatusDates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilterStatusDates As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilter As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFilters control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilters As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rptInvoices control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptInvoices As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
