'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3623
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.Dom.ProviderInvoices

    Partial Public Class ViewInvoiceVisitDetails

        '''<summary>
        '''lblProvider control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProvider As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblContract control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContract As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblServiceUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblServiceUser As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOrderReference control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOrderReference As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblWeekending control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWeekending As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblServiceType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblServiceType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVisitDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVisitDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblStartTimeClaimed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStartTimeClaimed As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDurationClaimed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDurationClaimed As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVisitCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVisitCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblNumberOfCarers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNumberOfCarers As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSecondaryVisit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSecondaryVisit As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSecondaryVisitAutoSet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSecondaryVisitAutoSet As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblManuallyAmended control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblManuallyAmended As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblActualStartTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblActualStartTime As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblActualDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblActualDuration As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rptCarers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptCarers As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
