'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3634
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.Admin.Dom

    Partial Public Class RateCategories

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''stdButtons1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents stdButtons1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''fsControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''pnlDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDescription As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDescription As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''pnlRegisterGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlRegisterGroup As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtRegisterGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRegisterGroup As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''pnlUom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlUom As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cboUom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboUom As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''cboPaymentToleranceGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboPaymentToleranceGroup As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''pnlOneUnitPerOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlOneUnitPerOrder As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''chkOneUnitPerOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkOneUnitPerOrder As Global.Target.Library.Web.Controls.CheckBoxEx

        '''<summary>
        '''pnlManualPayments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlManualPayments As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''chkManualPayments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkManualPayments As Global.Target.Library.Web.Controls.CheckBoxEx

        '''<summary>
        '''pnlCareProviderNotPaid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCareProviderNotPaid As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''chkCareProviderNotPaid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCareProviderNotPaid As Global.Target.Library.Web.Controls.CheckBoxEx

        '''<summary>
        '''pnlServiceType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlServiceType As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cboServiceType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboServiceType As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''pnlDayCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDayCategory As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cboDayCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboDayCategory As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''pnlTimeBand control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlTimeBand As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cboTimeBand control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboTimeBand As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''pnlConstructedAbbreviation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlConstructedAbbreviation As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtConstructedAbbreviation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtConstructedAbbreviation As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''pnlAbbreviationSuffix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAbbreviationSuffix As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtAbbreviationSuffix control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAbbreviationSuffix As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''pnlDomService control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDomService As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblService control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblService As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtService control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtService As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtFinanceCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFinanceCode As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtFinanceCode2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFinanceCode2 As Global.System.Web.UI.UserControl
    End Class
End Namespace
