'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.Admin.Dom

	Partial Public Class VisitCodeGroups

		'''<summary>
		'''lblError control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''stdButtons1 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents stdButtons1 As Global.System.Web.UI.UserControl

		'''<summary>
		'''fsControls control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents fsControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

		'''<summary>
		'''txtDescription control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtDescription As Global.Target.Library.Web.Controls.TextBoxEx

		'''<summary>
		'''chkRedundant control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkRedundant As Global.Target.Library.Web.Controls.CheckBoxEx

		'''<summary>
		'''phVisitCodes control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents phVisitCodes As Global.System.Web.UI.WebControls.PlaceHolder

		'''<summary>
		'''btnAddVisitCode control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents btnAddVisitCode As Global.System.Web.UI.WebControls.Button
	End Class
End Namespace
