'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.Dom.ProviderInvoice

    Partial Public Class ViewInvoicedVisit

        '''<summary>
        '''btnBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBack As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''btnView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnView As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''pSchedules control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pSchedules As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblProvider control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProvider As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblContract control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContract As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOrderRef control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOrderRef As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblServiceUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblServiceUser As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblWeekending control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblWeekending As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblServiceType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblServiceType As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblServiceTypeAmendment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblServiceTypeAmendment As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVisitDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVisitDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblStartTimeClaimed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStartTimeClaimed As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblStartTimeClaimedAmendment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStartTimeClaimedAmendment As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDurationClaimed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDurationClaimed As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPreRoundedDurationClaimed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPreRoundedDurationClaimed As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDurationClaimedAmendment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDurationClaimedAmendment As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVisitCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVisitCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblVisitCodeAmendment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblVisitCodeAmendment As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblNumberCarers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNumberCarers As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSecondaryVisit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSecondaryVisit As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSecondaryVisitAmendment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSecondaryVisitAmendment As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSecondaryVisitAutoSet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSecondaryVisitAutoSet As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblManuallyAmended control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblManuallyAmended As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblActualStartTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblActualStartTime As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblActualDuration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblActualDuration As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblActualDurationAmendment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblActualDurationAmendment As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rptCarers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptCarers As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
