'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.Dom.ProviderInvoice

    Partial Public Class ViewInvoiceLines

        '''<summary>
        '''btnBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''headerDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents headerDetails As Global.System.Web.UI.UserControl

        '''<summary>
        '''pnlDetailsSummaryVisitLevel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDetailsSummaryVisitLevel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''phDetailsSummaryVisitLevel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phDetailsSummaryVisitLevel As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''pnlDetailsManualPayment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDetailsManualPayment As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''phDetailsManualPayment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phDetailsManualPayment As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''pnlDetailsSummaryLevelExtranet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDetailsSummaryLevelExtranet As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''phDetailsSummaryLevelExtranet control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phDetailsSummaryLevelExtranet As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''ctrlInvoiceNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlInvoiceNotes As Global.System.Web.UI.UserControl
    End Class
End Namespace
