'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.Dom.Contracts

	Partial Public Class AuditLog

		'''<summary>
		'''cboTableName control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cboTableName As Global.Target.Library.Web.Controls.DropDownListEx

		'''<summary>
		'''dteDateFrom control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents dteDateFrom As Global.Target.Library.Web.Controls.TextBoxEx

		'''<summary>
		'''dteDateTo control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents dteDateTo As Global.Target.Library.Web.Controls.TextBoxEx
	End Class
End Namespace
