'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.Dom.Contracts

    Partial Public Class Header

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''stdButtons1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents stdButtons1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''fsCopyingFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsCopyingFrom As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''fsWarnings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsWarnings As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''fsControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNumber As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTitle As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDescription As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''Label1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''provider control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents provider As Global.System.Web.UI.UserControl

        '''<summary>
        '''dteStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteStartDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''dteEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteEndDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtEndReason control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEndReason As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtServiceGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtServiceGroup As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtAltRef control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAltRef As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''cboContractType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboContractType As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''client control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents client As Global.System.Web.UI.UserControl

        '''<summary>
        '''cboContractGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboContractGroup As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''cboAdministrativeArea control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboAdministrativeArea As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''cboRateFramework control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboRateFramework As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''chkUseEnhancedRateDays control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUseEnhancedRateDays As Global.Target.Library.Web.Controls.CheckBoxEx

        '''<summary>
        '''chkBankHolidayCover control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkBankHolidayCover As Global.Target.Library.Web.Controls.CheckBoxEx

        '''<summary>
        '''pnlChargeSU control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlChargeSU As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''chkChargeSU control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkChargeSU As Global.Target.Library.Web.Controls.CheckBoxEx

        '''<summary>
        '''chkDsoMaintExternal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDsoMaintExternal As Global.Target.Library.Web.Controls.CheckBoxEx

        '''<summary>
        '''chkProviderUnitCostOverride control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkProviderUnitCostOverride As Global.Target.Library.Web.Controls.CheckBoxEx

        '''<summary>
        '''cboVerificationText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboVerificationText As Global.Target.Library.Web.Controls.DropDownListEx
    End Class
End Namespace
