'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.Dom.Contracts

    Partial Public Class PaymentPlan

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''stdButtons1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents stdButtons1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''cpe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cpe As Global.AjaxControlToolkit.CollapsiblePanelExtender

        '''<summary>
        '''fsControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''fsHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsHeader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''pnlHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlHeader As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''LinkButton1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LinkButton1 As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''Image1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''pnlFirstPaymentDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlFirstPaymentDate As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''dteFirstPaymentDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteFirstPaymentDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''dteEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteEndDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''lblContractValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContractValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtContractValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtContractValue As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''lblTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblRunningTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRunningTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''fsFactors control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsFactors As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''pnlFinanceComponents control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlFinanceComponents As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlExpenditureAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlExpenditureAccount As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblExpenditureAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExpenditureAccount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''expenditureAccount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents expenditureAccount As Global.System.Web.UI.UserControl

        '''<summary>
        '''pnlRateCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlRateCategory As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblRateCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRateCategory As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboRateCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboRateCategory As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''pnlFrequency control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlFrequency As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblFrequency control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFrequency As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboFrequency control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboFrequency As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''pnlClientGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlClientGroup As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblClientGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblClientGroup As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''clientGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents clientGroup As Global.System.Web.UI.UserControl

        '''<summary>
        '''pnlClientSubGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlClientSubGroup As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblClientSubGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblClientSubGroup As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''clientSubGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents clientSubGroup As Global.System.Web.UI.UserControl

        '''<summary>
        '''pnlTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlTeam As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTeam As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''team control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents team As Global.System.Web.UI.UserControl

        '''<summary>
        '''pnlFinanceCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlFinanceCode As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblFinanceCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFinanceCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''financeCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents financeCode As Global.System.Web.UI.UserControl

        '''<summary>
        '''hidRunningTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidRunningTotal As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    End Class
End Namespace
