'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.FinanceCodeMatrix.Enquiry

    Partial Public Class Edit

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''stdButtons1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents stdButtons1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''fsControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''dteEffectiveDateFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteEffectiveDateFrom As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''dteEffectiveDateTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteEffectiveDateTo As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''optIncome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optIncome As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''lblIncome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblIncome As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''optExpenditure control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optExpenditure As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''lblFinanceCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFinanceCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtFinanceCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFinanceCode As Global.System.Web.UI.UserControl

        '''<summary>
        '''btnNewFinanceCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNewFinanceCode As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''fsFactors control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsFactors As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''pnlClientGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlClientGroup As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtClientGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtClientGroup As Global.System.Web.UI.UserControl

        '''<summary>
        '''pnlClientSubGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlClientSubGroup As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtClientSubGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtClientSubGroup As Global.System.Web.UI.UserControl

        '''<summary>
        '''pnlAgeRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlAgeRange As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtAgeRangeFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAgeRangeFrom As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtAgeRangeTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAgeRangeTo As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''pnlTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlTeam As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtTeam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTeam As Global.System.Web.UI.UserControl

        '''<summary>
        '''pnlProvider control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlProvider As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtProvider control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProvider As Global.System.Web.UI.UserControl

        '''<summary>
        '''pnlPrivateOrLA control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPrivateOrLA As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''optPrivate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optPrivate As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''optLA control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optLA As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''optBoth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optBoth As Global.System.Web.UI.HtmlControls.HtmlInputRadioButton

        '''<summary>
        '''pnlServiceType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlServiceType As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtServiceType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtServiceType As Global.System.Web.UI.UserControl

        '''<summary>
        '''pnlContractNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlContractNo As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtContract control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtContract As Global.System.Web.UI.UserControl

        '''<summary>
        '''pnlServiceOrderRef control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlServiceOrderRef As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtServiceOrderRef control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtServiceOrderRef As Global.Target.Library.Web.Controls.TextBoxEx
    End Class
End Namespace
