'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3634
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.Sds.DPContracts

    Partial Public Class EditPayment

        '''<summary>
        '''cp control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cp As Global.Target.Library.Web.Controls.CollapsiblePanel

        '''<summary>
        '''pnlPayment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPayment As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''stdButtons1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents stdButtons1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''hidTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidTitle As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidBudgetPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidBudgetPeriod As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidISSDS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidISSDS As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidClientID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidClientID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divExternalReference control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divExternalReference As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtExternalReference control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExternalReference As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''dteDateFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteDateFrom As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''hidDateFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidDateFrom As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''fldCurrentPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fldCurrentPeriod As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblCurrentDateRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentDateRange As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCurrentPaymentsHaveBeedPaid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentPaymentsHaveBeedPaid As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCurrentPaymentsWillBePaid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCurrentPaymentsWillBePaid As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''fldNextPeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fldNextPeriod As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblNextDateRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNextDateRange As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblNextPaymentsHaveBeedPaid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNextPaymentsHaveBeedPaid As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblNextPaymentsWillBePaid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNextPaymentsWillBePaid As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOverlappingPayments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOverlappingPayments As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboFrequency control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboFrequency As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''hidFrequency control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidFrequency As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''txtNumPayments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNumPayments As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''hidNumPayments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidNumPayments As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''txtDateTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDateTo As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''hidDateTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidDateTo As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''cboEndReason control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboEndReason As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''hidEndReason control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidEndReason As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''grpBreakdown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grpBreakdown As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''phPaymentBreakdown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phPaymentBreakdown As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''btnAddBreakdown control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAddBreakdown As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''pnlLegend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlLegend As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlLegendNotInSpendPlan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlLegendNotInSpendPlan As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblLegendNotInSpendPlan control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLegendNotInSpendPlan As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlLegendInSpendPlanNotDP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlLegendInSpendPlanNotDP As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblLegenedInSpendPlanNotDP control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLegenedInSpendPlanNotDP As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''txtAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAmount As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''hidAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidAmount As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''chkForceGross control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkForceGross As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''hidForceGross control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidForceGross As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''lblStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''optStatusProv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optStatusProv As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optStatusActive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optStatusActive As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optStatusSuspended control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optStatusSuspended As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''lblFinCode1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFinCode1 As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtFinCode1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFinCode1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''hdnFinanceCode1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdnFinanceCode1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''grpPaymentSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grpPaymentSummary As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spnPaidUpTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spnPaidUpTo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''hidPaidUpTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidPaidUpTo As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hidPaymentsMade control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hidPaymentsMade As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    End Class
End Namespace
