'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.ApplicationSystemSettings.Admin

    Partial Public Class SettingsEdit

        '''<summary>
        '''litPageError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPageError As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''pnlForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlForm As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''updProgress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents updProgress As Global.System.Web.UI.UpdateProgress

        '''<summary>
        '''upUpdater control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upUpdater As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''vldSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents vldSummary As Global.System.Web.UI.WebControls.ValidationSummary

        '''<summary>
        '''stdButtons1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents stdButtons1 As Global.Target.Web.Library.UserControls.StdButtons

        '''<summary>
        '''phSettingControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phSettingControls As Global.System.Web.UI.WebControls.PlaceHolder
    End Class
End Namespace
