'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3623
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.Dom.ProformaInvoice

    Partial Public Class InvoiceBatchBreadcrumb

        '''<summary>
        '''btnBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBack As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''batchLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents batchLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''viewBatch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents viewBatch As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''invoiceLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents invoiceLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''viewInvoice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents viewInvoice As Global.System.Web.UI.HtmlControls.HtmlAnchor

        '''<summary>
        '''visitLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents visitLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''viewCostedVisit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents viewCostedVisit As Global.System.Web.UI.HtmlControls.HtmlAnchor
    End Class
End Namespace
