'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.Dom.ProformaInvoice

    Partial Public Class ManualEnterInvoice

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''stdButtons1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents stdButtons1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''btnInvoiceLines control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnInvoiceLines As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''pScheduleHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pScheduleHeader As Global.Target.Abacus.Extranet.Apps.UserControls.PaymentScheduleHeader

        '''<summary>
        '''pnlInvoice control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlInvoice As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtProvider control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProvider As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtContract control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtContract As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtClient control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtClient As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''dteWeekEnding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteWeekEnding As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtReference control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReference As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtPaymentClaimed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPaymentClaimed As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtDirectIncome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDirectIncome As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtNoOfVisits control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNoOfVisits As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''txtNoOfHours control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNoOfHours As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''PnlVisits control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PnlVisits As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''tabStripVisits control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabStripVisits As Global.AjaxControlToolkit.TabContainer

        '''<summary>
        '''tobeRemovedAtRuntime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tobeRemovedAtRuntime As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''txtHidReference control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHidReference As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtHidName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHidName As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtHidId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtHidId As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtEditCareProviderRef control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEditCareProviderRef As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''txtEditCareProviderName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEditCareProviderName As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''txtEditCareProviderId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEditCareProviderId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''txtExistingCareWorkerList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExistingCareWorkerList As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''txtCopyToName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCopyToName As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtCopyToReference control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCopyToReference As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtCopyVisits control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCopyVisits As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtCopyToWeekDay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCopyToWeekDay As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtCollapsablePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCollapsablePanel As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txthidtabCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txthidtabCount As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''OriginalValueChanged control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OriginalValueChanged As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''EnableAddTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EnableAddTab As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''CollapsablePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CollapsablePanel As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''AddNewRow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents AddNewRow As Global.System.Web.UI.WebControls.HiddenField
    End Class
End Namespace
