'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.Dom.ProformaInvoice

    Partial Public Class ViewInvoices

        '''<summary>
        '''psHeader1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents psHeader1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''cpe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cpe As Global.Target.Library.Web.Controls.CollapsiblePanel

        '''<summary>
        '''pnlfilters control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlfilters As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cboMismatches control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboMismatches As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''cboQueried control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboQueried As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''txtTolerance control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTolerance As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''rdbDcrFilterDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdbDcrFilterDefault As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''rdbDcrFilterYes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdbDcrFilterYes As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''rdbDcrFilterNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rdbDcrFilterNo As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''btnRecalculate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnRecalculate As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''btnDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDelete As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''btnVerify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnVerify As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''btnUnVerify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUnVerify As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''rptPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptPrint As Global.System.Web.UI.UserControl
    End Class
End Namespace
