'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.Dom.ProformaInvoice

    Partial Public Class ViewNonVisitInvoices

        '''<summary>
        '''lblError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''stdButtons1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents stdButtons1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''cpDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cpDetail As Global.Target.Library.Web.Controls.CollapsiblePanel

        '''<summary>
        '''psHeader1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents psHeader1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''ucVoidPaymentDue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ucVoidPaymentDue As Global.System.Web.UI.UserControl

        '''<summary>
        '''fsControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsControls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''fsControlsLegend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsControlsLegend As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''rptProformas control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptProformas As Global.System.Web.UI.WebControls.Repeater

        '''<summary>
        '''btnRecalculate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnRecalculate As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''btnDeleteProforma control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnDeleteProforma As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''btnVerifyProforma control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnVerifyProforma As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''btnUnVerifyProforma control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnUnVerifyProforma As Global.System.Web.UI.HtmlControls.HtmlInputButton

        '''<summary>
        '''rptPrint control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptPrint As Global.System.Web.UI.UserControl
    End Class
End Namespace
