'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.UserControls

    Partial Public Class DomProviderInvoiceHeaderDetails

        '''<summary>
        '''pScheduleHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pScheduleHeader As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblProvider control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProvider As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblContract control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContract As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblForServiceUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblForServiceUser As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblServiceUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblServiceUser As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvoicePeriod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvoicePeriod As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvoiceNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvoiceNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReference control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReference As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvoiceTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvoiceTotal As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDirectIncome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDirectIncome As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvoiceStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvoiceStatus As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
