'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.UserControls

    Partial Public Class GenericServiceOrderSelector

        '''<summary>
        '''fsControlsLegend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fsControlsLegend As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''DSOAdditionalDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DSOAdditionalDetails As Global.System.Web.UI.UserControl

        '''<summary>
        '''detailWeekEndingDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents detailWeekEndingDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''costWeekEndingDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents costWeekEndingDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''btnAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnAdd As Global.System.Web.UI.HtmlControls.HtmlInputButton
    End Class
End Namespace
