'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.UserControls

    Partial Public Class InvoicedVisitsSelector

        '''<summary>
        '''btnView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnView As Global.System.Web.UI.HtmlControls.HtmlInputButton
    End Class
End Namespace
