'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Apps.UserControls

    Partial Public Class PaymentScheduleHeader

        '''<summary>
        '''pnlsingleLine control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlsingleLine As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblReferenceSingleLine control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReferenceSingleLine As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lnksingleLineLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnksingleLineLink As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lnksingleLineLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnksingleLineLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlPaymentSchedule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPaymentSchedule As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''pnlfieldset control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlfieldset As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblReference control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReference As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lnkPaymentSchedile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkPaymentSchedile As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblProvider control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProvider As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProviderRef control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProviderRef As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblProviderName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblProviderName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblcontract control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblcontract As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblContractNumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContractNumber As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblContractTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContractTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlPaymentFromTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPaymentFromTo As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblPaymentFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPaymentFrom As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDateFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDateFrom As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPaymentTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPaymentTo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDateTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDateTo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ExtraControls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ExtraControls As Global.System.Web.UI.WebControls.Panel
    End Class
End Namespace
