'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1378
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.CMS.Controls

    Partial Public Class CMSTree

        '''<summary>
        '''lblErrorMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrorMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''litTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litTitle As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''spanNewFolder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spanNewFolder As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spanMove control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spanMove As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spanDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spanDelete As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spanRefresh control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spanRefresh As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spanSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spanSelect As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''spanCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents spanCancel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''TreeView1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TreeView1 As Global.Target.Library.Web.Controls.TreeView
    End Class
End Namespace
