'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1378
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.CMS.Controls

    Partial Public Class PageAsEmailTemplate

        '''<summary>
        '''litHtmlTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litHtmlTitle As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''frmMain control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmMain As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''lnkHeaderLogo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkHeaderLogo As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''MPPageTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPPageTitle As Global.Target.Library.Web.MasterPages.ContentRegion

        '''<summary>
        '''lnkCannotView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkCannotView As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''MPPageOverview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPPageOverview As Global.Target.Library.Web.MasterPages.ContentRegion

        '''<summary>
        '''MPContent control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MPContent As Global.Target.Library.Web.MasterPages.ContentRegion
    End Class
End Namespace
