'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3623
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.Documents.UserControls

    Partial Public Class PrintDocumentsButton

        '''<summary>
        '''btnPrintDocuments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPrintDocuments As Global.System.Web.UI.HtmlControls.HtmlButton

        '''<summary>
        '''divDownloadContainer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divDownloadContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
