SET NOCOUNT ON
 
 
PRINT 'Inserting values into [WebAmendReqDataItem]'
                                                                                                                                   INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(1,'Provider','Local Provider ID',0,'Target.SP.Library.Apps.AmendReq.ProviderProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(2,'Provider','Website',0,'Target.SP.Library.Apps.AmendReq.ProviderProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(3,'Provider','Year End Date',0,'Target.SP.Library.Apps.AmendReq.ProviderProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(4,'Provider','Main Address',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(5,'Provider','Main Address Ward',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(6,'Provider','Main Address URNs',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(7,'Provider','Main Address Contact',0,'Target.SP.Library.Apps.AmendReq.ContactProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(8,'Provider','Contact Address',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(9,'Provider','Contact Address Ward',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(10,'Provider','Contact Address URNs',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(11,'Provider','Contact Address Contact',0,'Target.SP.Library.Apps.AmendReq.ContactProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(12,'Provider','Billing Address',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(13,'Provider','Billing Address Ward',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(14,'Provider','Billing Address URNs',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(15,'Provider','Billing Address Contact',0,'Target.SP.Library.Apps.AmendReq.ContactProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(16,'Service','Public Name',0,'Target.SP.Library.Apps.AmendReq.ServiceProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(17,'Service','Description',0,'Target.SP.Library.Apps.AmendReq.ServiceProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(18,'Service','Manager Address',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(19,'Service','Manager Address Ward',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(20,'Service','Manager Address URNs',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(21,'Service','Manager Address Contact',0,'Target.SP.Library.Apps.AmendReq.ContactProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(22,'Service','Emergency address',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(23,'Service','Emergency Address Ward',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(24,'Service','Emergency Address URNs',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(25,'Service','Emergency Address Contact',0,'Target.SP.Library.Apps.AmendReq.ContactProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(26,'Service','Contract Address',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(27,'Service','Contract Address Ward',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(28,'Service','Contract Address URNs',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(29,'Service','Contract Address Contact',0,'Target.SP.Library.Apps.AmendReq.ContactProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(30,'Service','Referral Address',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(31,'Service','Referral Address Ward',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(32,'Service','Referral Address URNs',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(33,'Service','Referral Address Contact',0,'Target.SP.Library.Apps.AmendReq.ContactProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(34,'Service','Referral Address 2',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(35,'Service','Referral Address 2 Ward',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(36,'Service','Referral Address 2 URNs',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(37,'Service','Referral Address 2 Contact',0,'Target.SP.Library.Apps.AmendReq.ContactProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(38,'Property','Alt Reference',0,'Target.SP.Library.Apps.AmendReq.PropertyProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(39,'Property','Meals Supplied',0,'Target.SP.Library.Apps.AmendReq.PropertyProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(40,'Property','Canteen On Site',0,'Target.SP.Library.Apps.AmendReq.PropertyProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(41,'Property','Self Catering',0,'Target.SP.Library.Apps.AmendReq.PropertyProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(42,'Property','Distances',0,'Target.SP.Library.Apps.AmendReq.PropertyProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(43,'Property','Address',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(44,'Property','Address Ward',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(45,'Property','Address URNs',0,'Target.SP.Library.Apps.AmendReq.AddressProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(46,'Property','Address Contact',0,'Target.SP.Library.Apps.AmendReq.ContactProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(47,'Client','Title',0,'Target.SP.Library.Apps.AmendReq.ClientProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(48,'Client','Forenames',0,'Target.SP.Library.Apps.AmendReq.ClientProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(49,'Client','Surname',0,'Target.SP.Library.Apps.AmendReq.ClientProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(50,'Client','Date Of Birth',0,'Target.SP.Library.Apps.AmendReq.ClientProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(51,'Client','NI Number',0,'Target.SP.Library.Apps.AmendReq.ClientProcessor, Target.SP.Library')
INSERT INTO [WebAmendReqDataItem] ([ID],[Entity],[Name],[EditMode],[AssemblyName])VALUES(52,'Subsidy','Provider Ref',0,'Target.SP.Library.Apps.AmendReq.ServiceAgreementProcessor, Target.SP.Library')

PRINT 'Done'
 
 
SET NOCOUNT OFF