SET NOCOUNT ON
 
 
PRINT 'Inserting values into [WebAmendReqDataField]'
                                                                                                                                   
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(1,1,'Local Provider ID','LocalProviderID')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(2,2,'Website','ProviderWebSite')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(3,3,'Year End Date','FinancialYearEndDate')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(4,4,'Address','Address')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(5,4,'Postcode','Postcode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(6,4,'Directions','Directions')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(7,4,'Disabled Access','DisabledAccess')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(8,4,'Also Used As',NULL)
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(9,5,'Ward','WardONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(10,6,'UPRN','UPRN')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(11,6,'USRN','USRN')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(12,7,'Type','ContactType')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(13,7,'Organisation','OrganisationName')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(14,7,'Title','Title')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(15,7,'Forenames','FirstNames')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(16,7,'Surname','Surname')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(17,7,'Position','Position')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(18,7,'Telephone No','TelephoneNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(19,7,'Fax No','FaxNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(20,7,'Mobile No','MobileNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(21,7,'Pager No','PagerNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(22,7,'Email Address','EmailAddress')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(23,7,'Web Address','WebAddress')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(24,7,'Comments','Comment')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(25,7,'Also Used As',NULL)
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(26,8,'Address','Address')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(27,8,'Postcode','Postcode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(28,8,'Directions','Directions')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(29,8,'Disabled Access','DisabledAccess')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(30,8,'Also Used As',NULL)
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(31,9,'Ward','WardONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(32,10,'UPRN','UPRN')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(33,10,'USRN','USRN')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(34,11,'Type','ContactType')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(35,11,'Organisation','OrganisationName')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(36,11,'Title','Title')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(37,11,'Forenames','FirstNames')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(38,11,'Surname','Surname')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(39,11,'Position','Position')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(40,11,'Telephone No','TelephoneNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(41,11,'Fax No','FaxNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(42,11,'Mobile No','MobileNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(43,11,'Pager No','PagerNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(44,11,'Email Address','EmailAddress')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(45,11,'Web Address','WebAddress')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(46,11,'Comments','Comment')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(47,11,'Also Used As',NULL)
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(48,12,'Address','Address')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(49,12,'Postcode','Postcode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(50,12,'Directions','Directions')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(51,12,'Disabled Access','DisabledAccess')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(52,12,'Also Used As',NULL)
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(53,13,'Ward','WardONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(54,14,'UPRN','UPRN')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(55,14,'USRN','USRN')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(56,15,'Type','ContactType')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(57,15,'Organisation','OrganisationName')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(58,15,'Title','Title')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(59,15,'Forenames','FirstNames')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(60,15,'Surname','Surname')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(61,15,'Position','Position')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(62,15,'Telephone No','TelephoneNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(63,15,'Fax No','FaxNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(64,15,'Mobile No','MobileNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(65,15,'Pager No','PagerNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(66,15,'Email Address','EmailAddress')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(67,15,'Web Address','WebAddress')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(68,15,'Comments','Comment')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(69,15,'Also Used As',NULL)
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(70,16,'Public Name','PublicServiceName')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(71,17,'Description','ServiceDescription')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(72,18,'Address','Address')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(73,18,'Postcode','Postcode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(74,18,'Directions','Directions')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(75,18,'Disabled Access','DisabledAccess')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(76,18,'Also Used As',NULL)
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(77,19,'Ward','WardONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(78,20,'UPRN','UPRN')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(79,20,'USRN','USRN')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(80,21,'Type','ContactType')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(81,21,'Organisation','OrganisationName')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(82,21,'Title','Title')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(83,21,'Forenames','FirstNames')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(84,21,'Surname','Surname')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(85,21,'Position','Position')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(86,21,'Telephone No','TelephoneNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(87,21,'Fax No','FaxNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(88,21,'Mobile No','MobileNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(89,21,'Pager No','PagerNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(90,21,'Email Address','EmailAddress')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(91,21,'Web Address','WebAddress')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(92,21,'Comments','Comment')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(93,21,'Also Used As',NULL)
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(94,22,'Address','Address')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(95,22,'Postcode','Postcode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(96,22,'Directions','Directions')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(97,22,'Disabled Access','DisabledAccess')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(98,22,'Also Used As',NULL)
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(99,23,'Ward','WardONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(100,24,'UPRN','UPRN')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(101,24,'USRN','USRN')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(102,25,'Type','ContactType')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(103,25,'Organisation','OrganisationName')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(104,25,'Title','Title')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(105,25,'Forenames','FirstNames')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(106,25,'Surname','Surname')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(107,25,'Position','Position')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(108,25,'Telephone No','TelephoneNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(109,25,'Fax No','FaxNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(110,25,'Mobile No','MobileNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(111,25,'Pager No','PagerNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(112,25,'Email Address','EmailAddress')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(113,25,'Web Address','WebAddress')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(114,25,'Comments','Comment')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(115,25,'Also Used As',NULL)
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(116,26,'Address','Address')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(117,26,'Postcode','Postcode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(118,26,'Directions','Directions')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(119,26,'Disabled Access','DisabledAccess')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(120,26,'Also Used As',NULL)
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(121,27,'Ward','WardONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(122,28,'UPRN','UPRN')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(123,28,'USRN','USRN')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(124,29,'Type','ContactType')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(125,29,'Organisation','OrganisationName')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(126,29,'Title','Title')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(127,29,'Forenames','FirstNames')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(128,29,'Surname','Surname')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(129,29,'Position','Position')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(130,29,'Telephone No','TelephoneNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(131,29,'Fax No','FaxNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(132,29,'Mobile No','MobileNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(133,29,'Pager No','PagerNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(134,29,'Email Address','EmailAddress')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(135,29,'Web Address','WebAddress')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(136,29,'Comments','Comment')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(137,29,'Also Used As',NULL)
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(138,30,'Address','Address')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(139,30,'Postcode','Postcode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(140,30,'Directions','Directions')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(141,30,'Disabled Access','DisabledAccess')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(142,30,'Also Used As',NULL)
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(143,31,'Ward','WardONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(144,32,'UPRN','UPRN')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(145,32,'USRN','USRN')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(146,33,'Type','ContactType')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(147,33,'Organisation','OrganisationName')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(148,33,'Title','Title')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(149,33,'Forenames','FirstNames')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(150,33,'Surname','Surname')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(151,33,'Position','Position')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(152,33,'Telephone No','TelephoneNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(153,33,'Fax No','FaxNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(154,33,'Mobile No','MobileNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(155,33,'Pager No','PagerNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(156,33,'Email Address','EmailAddress')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(157,33,'Web Address','WebAddress')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(158,33,'Comments','Comment')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(159,33,'Also Used As',NULL)
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(160,34,'Address','Address')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(161,34,'Postcode','Postcode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(162,34,'Directions','Directions')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(163,34,'Disabled Access','DisabledAccess')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(164,34,'Also Used As',NULL)
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(165,35,'Ward','WardONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(166,36,'UPRN','UPRN')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(167,36,'USRN','USRN')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(168,37,'Type','ContactType')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(169,37,'Organisation','OrganisationName')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(170,37,'Title','Title')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(171,37,'Forenames','FirstNames')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(172,37,'Surname','Surname')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(173,37,'Position','Position')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(174,37,'Telephone No','TelephoneNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(175,37,'Fax No','FaxNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(176,37,'Mobile No','MobileNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(177,37,'Pager No','PagerNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(178,37,'Email Address','EmailAddress')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(179,37,'Web Address','WebAddress')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(180,37,'Comments','Comment')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(181,37,'Also Used As',NULL)
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(182,38,'Alt Reference','AltRef')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(183,39,'Meals Supplied','MealsSuppliedStatus')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(184,40,'Canteen On Site','CanteenOnSiteStatus')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(185,41,'Self Catering','SelfCateringStatus')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(186,42,'Shops','DistanceToShops')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(187,42,'Train Station','DistanceToTrainStation')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(188,42,'Town Centre','DistanceToTownCentre')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(189,42,'GP','DistanceToGP')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(190,42,'Secondary School','DistanceToSecondarySchool')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(191,42,'Post Office','DistanceToPostOffice')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(192,42,'Bus Stop','DistanceToBusStop')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(193,42,'Social Centre','DistanceToSocialCentre')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(194,42,'Primary School','DistanceToPrimarySchool')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(195,43,'Address','Address')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(196,43,'Postcode','Postcode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(197,43,'Directions','Directions')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(198,43,'Disabled Access','DisabledAccess')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(199,43,'Also Used As',NULL)
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(200,44,'Ward','WardONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(201,45,'UPRN','UPRN')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(202,45,'USRN','USRN')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(203,46,'Type','ContactType')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(204,46,'Organisation','OrganisationName')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(205,46,'Title','Title')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(206,46,'Forenames','FirstNames')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(207,46,'Surname','Surname')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(208,46,'Position','Position')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(209,46,'Telephone No','TelephoneNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(210,46,'Fax No','FaxNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(211,46,'Mobile No','MobileNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(212,46,'Pager No','PagerNumber')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(213,46,'Email Address','EmailAddress')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(214,46,'Web Address','WebAddress')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(215,46,'Comments','Comment')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(216,46,'Also Used As',NULL)
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(217,47,'Title','Title')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(218,48,'Forenames','FirstName')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(219,49,'Surname','Surname')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(220,50,'Date Of Birth','DateOfBirth')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(221,51,'NI Number','NationalInsuranceNo')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(222,52,'Provider Ref','AltReference')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(223,5,'Admin Authority','AdminAuthorityONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(224,5,'District','DistrictONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(225,9,'Admin Authority','AdminAuthorityONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(226,9,'District','DistrictONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(227,13,'Admin Authority','AdminAuthorityONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(228,13,'District','DistrictONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(229,19,'Admin Authority','AdminAuthorityONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(230,19,'District','DistrictONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(231,23,'Admin Authority','AdminAuthorityONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(232,23,'District','DistrictONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(233,27,'Admin Authority','AdminAuthorityONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(234,27,'District','DistrictONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(235,31,'Admin Authority','AdminAuthorityONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(236,31,'District','DistrictONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(237,35,'Admin Authority','AdminAuthorityONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(238,35,'District','DistrictONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(239,44,'Admin Authority','AdminAuthorityONSCode')
INSERT INTO [WebAmendReqDataField] ([ID],[WebAmendReqDataItemID],[Name],[PropertyName])VALUES(240,44,'District','DistrictONSCode')

PRINT 'Done'
 
 
SET NOCOUNT OFF