if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[spxSPServiceUserStatement_FetchXML]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[spxSPServiceUserStatement_FetchXML]
GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO


CREATE  PROCEDURE [dbo].[spxSPServiceUserStatement_FetchXML]
	@intServiceID INT, 
	@intClientID INT, 
	@intUserID INT,
	@dteDateFrom DATETIME = NULL,
	@dteDateTo DATETIME = NULL
AS

-- statement period
SELECT 1 AS tag, NULL AS parent,
	@dteDateFrom AS [Statement!1!DateFrom!element],
	@dteDateTo AS [Statement!1!DateTo!element],
	NULL AS [Council!2!Name!xml], 
	NULL AS [Council!2!Address!xml],
	NULL AS [Council!2!Postcode!element],
	NULL AS [Council!2!ContactTitle!element],
	NULL AS [Council!2!ContactFirstNames!xml], 
	NULL AS [Council!2!ContactSurname!xml], 
	NULL AS [Council!2!Phone!element],
	NULL AS [Council!2!Fax!element],
	NULL AS [Council!2!Email!element],
	NULL AS [Provider!3!Name!xml],
	NULL AS [Provider!3!Reference!element],
	NULL AS [Provider!3!CreditorReference!element],
	NULL AS [Provider!3!Address!xml],
	NULL AS [Provider!3!Postcode!element],
	NULL AS [Provider!3!ContactTitle!element],
	NULL AS [Provider!3!ContactFirstNames!xml], 
	NULL AS [Provider!3!ContactSurname!xml], 
	NULL AS [Provider!3!Phone!element],
	NULL AS [Provider!3!Fax!element],
	NULL AS [Provider!3!Email!element],
	NULL AS [Service!4!Type!element], 
	NULL AS [Service!4!Reference!element], 
	NULL AS [Service!4!Name!xml],
	NULL AS [ServiceUser!5!Title],
	NULL AS [ServiceUser!5!FirstNames!xml], 
	NULL AS [ServiceUser!5!Surname!xml],
	NULL AS [ServiceAgreement!6!Reference!xml],
	NULL AS [ServiceAgreement!6!AltReference!xml],
	NULL AS [ServiceAgreement!6!DateFrom!element],
	NULL AS [ServiceAgreement!6!DateTo!element],
	NULL AS [ServiceAgreement!6!HBReference!xml],
	NULL AS [ServiceAgreement!6!PCReference!xml],
	NULL AS [ServiceAgreement!6!PropertyReference!xml],
	NULL AS [ServiceAgreement!6!PropertyReference!xml],
	NULL AS [ServiceAgreement!6!PropertyName!xml],
	NULL AS [ServiceAgreement!6!PropertyAddress!xml],
	NULL AS [ServiceAgreement!6!PropertyPostcode!element],
	NULL AS [Remittance!7!ID],
	NULL AS [Remittance!7!Reference!xml],
	NULL AS [Remittance!7!BatchRef!xml],
	NULL AS [Remittance!7!DateFrom!element],
	NULL AS [Remittance!7!DateTo!element],
	NULL AS [Remittance!7!TotalValue!element],
	NULL AS [Remittance!7!VAT!element],
	NULL AS [Remittance!7!NetValue!element],
	NULL AS [RemittanceLine!8!ID],
	NULL AS [RemittanceLine!8!Type],
	NULL AS [RemittanceLine!8!Comment!xml],
	NULL AS [RemittanceLine!8!DateFrom!element],
	NULL AS [RemittanceLine!8!DateTo!element],
	NULL AS [RemittanceLine!8!Value!element],
	NULL AS [RemittanceLine!8!VAT!element],
	NULL AS [RemittanceLine!8!NetValue!element],
	NULL AS [RemittanceLine!8!Reference!xml]
FROM SystemInfo

UNION ALL

-- council details
SELECT TOP 1 2 AS tag, 1 AS parent,
	NULL AS [Statement!1!DateFrom!element],
	NULL AS [Statement!1!DateTo!element],
	'<![CDATA[' + si.SiteName + ']]>' AS [Council!2!Name!xml], 
	'<![CDATA[' + CONVERT(VARCHAR(8000), a.Address) + ']]>' AS [Council!2!Address!xml],
	a.Postcode AS [Council!2!Postcode!element],
	c.Title AS [Council!2!ContactTitle!element],
	'<![CDATA[' + c.FirstNames + ']]>' AS [Council!2!ContactFirstNames!xml], 
	'<![CDATA[' + c.Surname + ']]>' AS [Council!2!ContactSurname!xml], 
	c.TelephoneNumber AS [Council!2!Phone!element],
	c.FaxNumber AS [Council!2!Fax!element],
	c.EmailAddress AS [Council!2!Email!element],
	NULL AS [Provider!3!Name!xml],
	NULL AS [Provider!3!Reference!element],
	NULL AS [Provider!3!CreditorReference!element],
	NULL AS [Provider!3!Address!xml],
	NULL AS [Provider!3!Postcode!element],
	NULL AS [Provider!3!ContactTitle!element],
	NULL AS [Provider!3!ContactFirstNames!xml], 
	NULL AS [Provider!3!ContactSurname!xml], 
	NULL AS [Provider!3!Phone!element],
	NULL AS [Provider!3!Fax!element],
	NULL AS [Provider!3!Email!element],
	NULL AS [Service!4!Type!element], 
	NULL AS [Service!4!Reference!element], 
	NULL AS [Service!4!Name!xml],
	NULL AS [ServiceUser!5!Title],
	NULL AS [ServiceUser!5!FirstNames!xml], 
	NULL AS [ServiceUser!5!Surname!xml],
	NULL AS [ServiceAgreement!6!Reference!xml],
	NULL AS [ServiceAgreement!6!AltReference!xml],
	NULL AS [ServiceAgreement!6!DateFrom!element],
	NULL AS [ServiceAgreement!6!DateTo!element],
	NULL AS [ServiceAgreement!6!HBReference!xml],
	NULL AS [ServiceAgreement!6!PCReference!xml],
	NULL AS [ServiceAgreement!6!PropertyReference!xml],
	NULL AS [ServiceAgreement!6!PropertyReference!xml],
	NULL AS [ServiceAgreement!6!PropertyName!xml],
	NULL AS [ServiceAgreement!6!PropertyAddress!xml],
	NULL AS [ServiceAgreement!6!PropertyPostcode!element],
	NULL AS [Remittance!7!ID],
	NULL AS [Remittance!7!Reference!xml],
	NULL AS [Remittance!7!BatchRef!xml],
	NULL AS [Remittance!7!DateFrom!element],
	NULL AS [Remittance!7!DateTo!element],
	NULL AS [Remittance!7!TotalValue!element],
	NULL AS [Remittance!7!VAT!element],
	NULL AS [Remittance!7!NetValue!element],
	NULL AS [RemittanceLine!8!ID],
	NULL AS [RemittanceLine!8!Type],
	NULL AS [RemittanceLine!8!Comment!xml],
	NULL AS [RemittanceLine!8!DateFrom!element],
	NULL AS [RemittanceLine!8!DateTo!element],
	NULL AS [RemittanceLine!8!Value!element],
	NULL AS [RemittanceLine!8!VAT!element],
	NULL AS [RemittanceLine!8!NetValue!element],
	NULL AS [RemittanceLine!8!Reference!xml]
FROM SystemInfo AS si
	LEFT OUTER JOIN SPAddress AS a ON (a.[ID] = si.SPCouncilAddressID)
	LEFT OUTER JOIN SPContact AS c ON (c.[ID] = si.SPCouncilContactID)
	LEFT OUTER JOIN SPAdminAuthority AS aa ON (aa.Value = a.AAONSCode)

UNION ALL

-- provider details
SELECT 3 AS tag, 1 AS parent,
	NULL AS [Statement!1!DateFrom!element],
	NULL AS [Statement!1!DateTo!element],
	NULL AS [Council!2!Name!xml], 
	NULL AS [Council!2!Address!xml],
	NULL AS [Council!2!Postcode!element],
	NULL AS [Council!2!ContactTitle!element],
	NULL AS [Council!2!ContactFirstNames!xml], 
	NULL AS [Council!2!ContactSurname!xml], 
	NULL AS [Council!2!Phone!element],
	NULL AS [Council!2!Fax!element],
	NULL AS [Council!2!Email!element],
	'<![CDATA[' + p.[Name] + ']]>' AS [Provider!3!Name!xml],
	p.Reference AS [Provider!3!Reference!element],
	p.CreditorsReference AS [Provider!3!CreditorReference!element],
	'<![CDATA[' + CONVERT(VARCHAR(8000), a.Address) + ']]>' AS [Provider!3!Address!xml],
	a.PostCode AS [Provider!3!Postcode!element],
	c.Title AS [Provider!3!ContactTitle!element],
	'<![CDATA[' + c.FirstNames + ']]>' AS [Provider!3!ContactFirstNames!xml], 
	'<![CDATA[' + c.Surname + ']]>' AS [Provider!3!ContactSurname!xml], 
	c.TelephoneNumber AS [Provider!3!Phone!element],
	c.FaxNumber AS [Provider!3!Fax!element],
	c.EmailAddress AS [Provider!3!Email!element],
	NULL AS [Service!4!Type!element], 
	NULL AS [Service!4!Reference!element], 
	NULL AS [Service!4!Name!xml],
	NULL AS [ServiceUser!5!Title],
	NULL AS [ServiceUser!5!FirstNames!xml], 
	NULL AS [ServiceUser!5!Surname!xml],
	NULL AS [ServiceAgreement!6!Reference!xml],
	NULL AS [ServiceAgreement!6!AltReference!xml],
	NULL AS [ServiceAgreement!6!DateFrom!element],
	NULL AS [ServiceAgreement!6!DateTo!element],
	NULL AS [ServiceAgreement!6!HBReference!xml],
	NULL AS [ServiceAgreement!6!PCReference!xml],
	NULL AS [ServiceAgreement!6!PropertyReference!xml],
	NULL AS [ServiceAgreement!6!PropertyReference!xml],
	NULL AS [ServiceAgreement!6!PropertyName!xml],
	NULL AS [ServiceAgreement!6!PropertyAddress!xml],
	NULL AS [ServiceAgreement!6!PropertyPostcode!element],
	NULL AS [Remittance!7!ID],
	NULL AS [Remittance!7!Reference!xml],
	NULL AS [Remittance!7!BatchRef!xml],
	NULL AS [Remittance!7!DateFrom!element],
	NULL AS [Remittance!7!DateTo!element],
	NULL AS [Remittance!7!TotalValue!element],
	NULL AS [Remittance!7!VAT!element],
	NULL AS [Remittance!7!NetValue!element],
	NULL AS [RemittanceLine!8!ID],
	NULL AS [RemittanceLine!8!Type],
	NULL AS [RemittanceLine!8!Comment!xml],
	NULL AS [RemittanceLine!8!DateFrom!element],
	NULL AS [RemittanceLine!8!DateTo!element],
	NULL AS [RemittanceLine!8!Value!element],
	NULL AS [RemittanceLine!8!VAT!element],
	NULL AS [RemittanceLine!8!NetValue!element],
	NULL AS [RemittanceLine!8!Reference!xml]
FROM SPProvider AS p
	INNER JOIN SPService AS s ON (s.ProviderID = p.[ID])
	LEFT OUTER JOIN SPAddress AS a ON (COALESCE(p.BillingAddressID, p.ProviderAddressID) = a.[ID]) 
	LEFT OUTER JOIN SPContact AS c ON (p.ProviderContactID = c.[ID])
WHERE s.[ID] = @intServiceID

UNION ALL

-- service details
SELECT 4 AS tag, 1 AS parent,
	NULL AS [Statement!1!DateFrom!element],
	NULL AS [Statement!1!DateTo!element],
	NULL AS [Council!2!Name!xml], 
	NULL AS [Council!2!Address!xml],
	NULL AS [Council!2!Postcode!element],
	NULL AS [Council!2!ContactTitle!element],
	NULL AS [Council!2!ContactFirstNames!xml], 
	NULL AS [Council!2!ContactSurname!xml], 
	NULL AS [Council!2!Phone!element],
	NULL AS [Council!2!Fax!element],
	NULL AS [Council!2!Email!element],
	NULL AS [Provider!3!Name!xml],
	NULL AS [Provider!3!Reference!element],
	NULL AS [Provider!3!CreditorReference!element],
	NULL AS [Provider!3!Address!xml],
	NULL AS [Provider!3!Postcode!element],
	NULL AS [Provider!3!ContactTitle!element],
	NULL AS [Provider!3!ContactFirstNames!xml], 
	NULL AS [Provider!3!ContactSurname!xml], 
	NULL AS [Provider!3!Phone!element],
	NULL AS [Provider!3!Fax!element],
	NULL AS [Provider!3!Email!element],
	ISNULL(t.Value, 'Unspecified Service Type') AS [Service!4!Type!element], 
	s.Reference AS [Service!4!Reference!element], 
	'<![CDATA[' + s.[Name] + ']]>' AS [Service!4!Name!xml],
	NULL AS [ServiceUser!5!Title],
	NULL AS [ServiceUser!5!FirstNames!xml], 
	NULL AS [ServiceUser!5!Surname!xml],
	NULL AS [ServiceAgreement!6!Reference!xml],
	NULL AS [ServiceAgreement!6!AltReference!xml],
	NULL AS [ServiceAgreement!6!DateFrom!element],
	NULL AS [ServiceAgreement!6!DateTo!element],
	NULL AS [ServiceAgreement!6!HBReference!xml],
	NULL AS [ServiceAgreement!6!PCReference!xml],
	NULL AS [ServiceAgreement!6!PropertyReference!xml],
	NULL AS [ServiceAgreement!6!PropertyReference!xml],
	NULL AS [ServiceAgreement!6!PropertyName!xml],
	NULL AS [ServiceAgreement!6!PropertyAddress!xml],
	NULL AS [ServiceAgreement!6!PropertyPostcode!element],
	NULL AS [Remittance!7!ID],
	NULL AS [Remittance!7!Reference!xml],
	NULL AS [Remittance!7!BatchRef!xml],
	NULL AS [Remittance!7!DateFrom!element],
	NULL AS [Remittance!7!DateTo!element],
	NULL AS [Remittance!7!TotalValue!element],
	NULL AS [Remittance!7!VAT!element],
	NULL AS [Remittance!7!NetValue!element],
	NULL AS [RemittanceLine!8!ID],
	NULL AS [RemittanceLine!8!Type],
	NULL AS [RemittanceLine!8!Comment!xml],
	NULL AS [RemittanceLine!8!DateFrom!element],
	NULL AS [RemittanceLine!8!DateTo!element],
	NULL AS [RemittanceLine!8!Value!element],
	NULL AS [RemittanceLine!8!VAT!element],
	NULL AS [RemittanceLine!8!NetValue!element],
	NULL AS [RemittanceLine!8!Reference!xml]
FROM SPService AS s
	LEFT OUTER JOIN SPServiceType AS t ON (t.[ID] = s.ServiceTypeID)
WHERE s.[ID] = @intServiceID

UNION ALL

-- client details
SELECT 5 AS tag, 1 AS parent,
	NULL AS [Statement!1!DateFrom!element],
	NULL AS [Statement!1!DateTo!element],
	NULL AS [Council!2!Name!xml], 
	NULL AS [Council!2!Address!xml],
	NULL AS [Council!2!Postcode!element],
	NULL AS [Council!2!ContactTitle!element],
	NULL AS [Council!2!ContactFirstNames!xml], 
	NULL AS [Council!2!ContactSurname!xml], 
	NULL AS [Council!2!Phone!element],
	NULL AS [Council!2!Fax!element],
	NULL AS [Council!2!Email!element],
	NULL AS [Provider!3!Name!xml],
	NULL AS [Provider!3!Reference!element],
	NULL AS [Provider!3!CreditorReference!element],
	NULL AS [Provider!3!Address!xml],
	NULL AS [Provider!3!Postcode!element],
	NULL AS [Provider!3!ContactTitle!element],
	NULL AS [Provider!3!ContactFirstNames!xml], 
	NULL AS [Provider!3!ContactSurname!xml], 
	NULL AS [Provider!3!Phone!element],
	NULL AS [Provider!3!Fax!element],
	NULL AS [Provider!3!Email!element],
	NULL AS [Service!4!Type!element], 
	NULL AS [Service!4!Reference!element], 
	NULL AS [Service!4!Name!xml],
	t.[Description] AS [ServiceUser!5!Title],
	'<![CDATA[' + cd.FirstNames + ']]>' AS [ServiceUser!5!FirstNames!xml], 
	'<![CDATA[' + cd.LastName + ']]>' AS [ServiceUser!5!Surname!xml],
	NULL AS [ServiceAgreement!6!Reference!xml],
	NULL AS [ServiceAgreement!6!AltReference!xml],
	NULL AS [ServiceAgreement!6!DateFrom!element],
	NULL AS [ServiceAgreement!6!DateTo!element],
	NULL AS [ServiceAgreement!6!HBReference!xml],
	NULL AS [ServiceAgreement!6!PCReference!xml],
	NULL AS [ServiceAgreement!6!PropertyReference!xml],
	NULL AS [ServiceAgreement!6!PropertyReference!xml],
	NULL AS [ServiceAgreement!6!PropertyName!xml],
	NULL AS [ServiceAgreement!6!PropertyAddress!xml],
	NULL AS [ServiceAgreement!6!PropertyPostcode!element],
	NULL AS [Remittance!7!ID],
	NULL AS [Remittance!7!Reference!xml],
	NULL AS [Remittance!7!BatchRef!xml],
	NULL AS [Remittance!7!DateFrom!element],
	NULL AS [Remittance!7!DateTo!element],
	NULL AS [Remittance!7!TotalValue!element],
	NULL AS [Remittance!7!VAT!element],
	NULL AS [Remittance!7!NetValue!element],
	NULL AS [RemittanceLine!8!ID],
	NULL AS [RemittanceLine!8!Type],
	NULL AS [RemittanceLine!8!Comment!xml],
	NULL AS [RemittanceLine!8!DateFrom!element],
	NULL AS [RemittanceLine!8!DateTo!element],
	NULL AS [RemittanceLine!8!Value!element],
	NULL AS [RemittanceLine!8!VAT!element],
	NULL AS [RemittanceLine!8!NetValue!element],
	NULL AS [RemittanceLine!8!Reference!xml]
FROM ClientDetail AS cd
	LEFT OUTER JOIN lookup AS t ON (t.[ID] = cd.Title AND t.Type = 'TITLE')
WHERE cd.[ID] = @intClientID

UNION ALL

-- service agreement
SELECT TOP 1 6 AS tag, 1 AS parent,
	NULL AS [Statement!1!DateFrom!element],
	NULL AS [Statement!1!DateTo!element],
	NULL AS [Council!2!Name!xml], 
	NULL AS [Council!2!Address!xml],
	NULL AS [Council!2!Postcode!element],
	NULL AS [Council!2!ContactTitle!element],
	NULL AS [Council!2!ContactFirstNames!xml], 
	NULL AS [Council!2!ContactSurname!xml], 
	NULL AS [Council!2!Phone!element],
	NULL AS [Council!2!Fax!element],
	NULL AS [Council!2!Email!element],
	NULL AS [Provider!3!Name!xml],
	NULL AS [Provider!3!Reference!element],
	NULL AS [Provider!3!CreditorReference!element],
	NULL AS [Provider!3!Address!xml],
	NULL AS [Provider!3!Postcode!element],
	NULL AS [Provider!3!ContactTitle!element],
	NULL AS [Provider!3!ContactFirstNames!xml], 
	NULL AS [Provider!3!ContactSurname!xml], 
	NULL AS [Provider!3!Phone!element],
	NULL AS [Provider!3!Fax!element],
	NULL AS [Provider!3!Email!element],
	NULL AS [Service!4!Type!element], 
	NULL AS [Service!4!Reference!element], 
	NULL AS [Service!4!Name!xml],
	NULL AS [ServiceUser!5!Title],
	NULL AS [ServiceUser!5!FirstNames!xml], 
	NULL AS [ServiceUser!5!Surname!xml],
	'<![CDATA[' + sa.Reference + ']]>' AS [ServiceAgreement!6!Reference!xml],
	'<![CDATA[' + sa.AltReference + ']]>' AS [ServiceAgreement!6!AltReference!xml],
	sa.DateFrom AS [ServiceAgreement!6!DateFrom!element],
	sa.DateTo AS [ServiceAgreement!6!DateTo!element],
	'<![CDATA[' + sa.HBReference + ']]>' AS [ServiceAgreement!6!HBReference!xml],
	'<![CDATA[' + sa.FCReference + ']]>' AS [ServiceAgreement!6!PCReference!xml],
	'<![CDATA[' + p.Reference + ']]>' AS [ServiceAgreement!6!PropertyReference!xml],
	'<![CDATA[' + p.AltRef + ']]>' AS [ServiceAgreement!6!PropertyReference!xml],
	'<![CDATA[' + p.[Name] + ']]>' AS [ServiceAgreement!6!PropertyName!xml],
	'<![CDATA[' + CONVERT(VARCHAR(8000), a.Address) + ']]>' AS [ServiceAgreement!6!PropertyAddress!xml],
	a.Postcode AS [ServiceAgreement!6!PropertyPostcode!element],
	NULL AS [Remittance!7!ID],
	NULL AS [Remittance!7!Reference!xml],
	NULL AS [Remittance!7!BatchRef!xml],
	NULL AS [Remittance!7!DateFrom!element],
	NULL AS [Remittance!7!DateTo!element],
	NULL AS [Remittance!7!TotalValue!element],
	NULL AS [Remittance!7!VAT!element],
	NULL AS [Remittance!7!NetValue!element],
	NULL AS [RemittanceLine!8!ID],
	NULL AS [RemittanceLine!8!Type],
	NULL AS [RemittanceLine!8!Comment!xml],
	NULL AS [RemittanceLine!8!DateFrom!element],
	NULL AS [RemittanceLine!8!DateTo!element],
	NULL AS [RemittanceLine!8!Value!element],
	NULL AS [RemittanceLine!8!VAT!element],
	NULL AS [RemittanceLine!8!NetValue!element],
	NULL AS [RemittanceLine!8!Reference!xml]
FROM SPServiceAgreement AS sa
	INNER JOIN SPProperty AS p ON (p.[ID] = sa.PropertyID)
	LEFT OUTER JOIN SPAddress AS a ON (a.[ID] = p.AddressID)
WHERE sa.ServiceID = @intServiceID
AND sa.ClientID = @intClientID

UNION ALL 

-- remittance headers
SELECT DISTINCT 7 AS tag, 1 AS parent,
	NULL AS [Statement!1!DateFrom!element],
	NULL AS [Statement!1!DateTo!element],
	NULL AS [Council!2!Name!xml], 
	NULL AS [Council!2!Address!xml],
	NULL AS [Council!2!Postcode!element],
	NULL AS [Council!2!ContactTitle!element],
	NULL AS [Council!2!ContactFirstNames!xml], 
	NULL AS [Council!2!ContactSurname!xml], 
	NULL AS [Council!2!Phone!element],
	NULL AS [Council!2!Fax!element],
	NULL AS [Council!2!Email!element],
	NULL AS [Provider!3!Name!xml],
	NULL AS [Provider!3!Reference!element],
	NULL AS [Provider!3!CreditorReference!element],
	NULL AS [Provider!3!Address!xml],
	NULL AS [Provider!3!Postcode!element],
	NULL AS [Provider!3!ContactTitle!element],
	NULL AS [Provider!3!ContactFirstNames!xml], 
	NULL AS [Provider!3!ContactSurname!xml], 
	NULL AS [Provider!3!Phone!element],
	NULL AS [Provider!3!Fax!element],
	NULL AS [Provider!3!Email!element],
	NULL AS [Service!4!Type!element], 
	NULL AS [Service!4!Reference!element], 
	NULL AS [Service!4!Name!xml],
	NULL AS [ServiceUser!5!Title],
	NULL AS [ServiceUser!5!FirstNames!xml], 
	NULL AS [ServiceUser!5!Surname!xml],
	NULL AS [ServiceAgreement!6!Reference!xml],
	NULL AS [ServiceAgreement!6!AltReference!xml],
	NULL AS [ServiceAgreement!6!DateFrom!element],
	NULL AS [ServiceAgreement!6!DateTo!element],
	NULL AS [ServiceAgreement!6!HBReference!xml],
	NULL AS [ServiceAgreement!6!PCReference!xml],
	NULL AS [ServiceAgreement!6!PropertyReference!xml],
	NULL AS [ServiceAgreement!6!PropertyReference!xml],
	NULL AS [ServiceAgreement!6!PropertyName!xml],
	NULL AS [ServiceAgreement!6!PropertyAddress!xml],
	NULL AS [ServiceAgreement!6!PropertyPostcode!element],
	r.[ID] AS [Remittance!7!ID],
	'<![CDATA[' + r.Reference + ']]>' AS [Remittance!7!Reference!xml],
	'<![CDATA[' + r.BatchRef + ']]>' AS [Remittance!7!BatchRef!xml],
	r.DateFrom AS [Remittance!7!DateFrom!element],
	r.DateTo AS [Remittance!7!DateTo!element],
	r.TotalValue AS [Remittance!7!TotalValue!element],
	r.VAT AS [Remittance!7!VAT!element],
	(r.TotalValue - r.VAT) AS [Remittance!7!NetValue!element],
	NULL AS [RemittanceLine!8!ID],
	NULL AS [RemittanceLine!8!Type],
	NULL AS [RemittanceLine!8!Comment!xml],
	NULL AS [RemittanceLine!8!DateFrom!element],
	NULL AS [RemittanceLine!8!DateTo!element],
	NULL AS [RemittanceLine!8!Value!element],
	NULL AS [RemittanceLine!8!VAT!element],
	NULL AS [RemittanceLine!8!NetValue!element],
	NULL AS [RemittanceLine!8!Reference!xml]
FROM SPRemittance AS r
	INNER JOIN SPRemittanceDetail AS rd ON (rd.RemittanceID = r.[ID])
	INNER JOIN SPSubsidyAgreement AS sub ON (sub.[ID] = rd.RelatedID)
	INNER JOIN SPServiceAgreement AS sa ON (sa.[ID] = sub.ServiceAgreementID)
	INNER JOIN User_SPService AS us ON (us.SPServiceID = sa.ServiceID)
WHERE r.InterfaceLogID IS NOT NULL
AND (@intServiceID IS NULL OR (@intServiceID IS NOT NULL AND sa.ServiceID = @intServiceID))
AND us.UserID = @intUserID
AND sa.ClientID = @intClientID
AND (@dteDateFrom IS NULL OR (@dteDateFrom IS NOT NULL AND DATEDIFF(dd, @dteDateFrom, r.DateTo) >= 0))
AND (@dteDateTo IS NULL OR (@dteDateTo IS NOT NULL AND DATEDIFF(dd, @dteDateTo, r.DateFrom) <= 0))

UNION ALL

-- remittance detail
SELECT 8 AS tag, 7 AS parent,
	NULL AS [Statement!1!DateFrom!element],
	NULL AS [Statement!1!DateTo!element],
	NULL AS [Council!2!Name!xml], 
	NULL AS [Council!2!Address!xml],
	NULL AS [Council!2!Postcode!element],
	NULL AS [Council!2!ContactTitle!element],
	NULL AS [Council!2!ContactFirstNames!xml], 
	NULL AS [Council!2!ContactSurname!xml], 
	NULL AS [Council!2!Phone!element],
	NULL AS [Council!2!Fax!element],
	NULL AS [Council!2!Email!element],
	NULL AS [Provider!3!Name!xml],
	NULL AS [Provider!3!Reference!element],
	NULL AS [Provider!3!CreditorReference!element],
	NULL AS [Provider!3!Address!xml],
	NULL AS [Provider!3!Postcode!element],
	NULL AS [Provider!3!ContactTitle!element],
	NULL AS [Provider!3!ContactFirstNames!xml], 
	NULL AS [Provider!3!ContactSurname!xml], 
	NULL AS [Provider!3!Phone!element],
	NULL AS [Provider!3!Fax!element],
	NULL AS [Provider!3!Email!element],
	NULL AS [Service!4!Type!element], 
	NULL AS [Service!4!Reference!element], 
	NULL AS [Service!4!Name!xml],
	NULL AS [ServiceUser!5!Title],
	NULL AS [ServiceUser!5!FirstNames!xml], 
	NULL AS [ServiceUser!5!Surname!xml],
	NULL AS [ServiceAgreement!6!Reference!xml],
	NULL AS [ServiceAgreement!6!AltReference!xml],
	NULL AS [ServiceAgreement!6!DateFrom!element],
	NULL AS [ServiceAgreement!6!DateTo!element],
	NULL AS [ServiceAgreement!6!HBReference!xml],
	NULL AS [ServiceAgreement!6!PCReference!xml],
	NULL AS [ServiceAgreement!6!PropertyReference!xml],
	NULL AS [ServiceAgreement!6!PropertyReference!xml],
	NULL AS [ServiceAgreement!6!PropertyName!xml],
	NULL AS [ServiceAgreement!6!PropertyAddress!xml],
	NULL AS [ServiceAgreement!6!PropertyPostcode!element],
	r.[ID] AS [Remittance!7!ID],
	NULL AS [Remittance!7!Reference!xml],
	NULL AS [Remittance!7!BatchRef!xml],
	NULL AS [Remittance!7!DateFrom!element],
	NULL AS [Remittance!7!DateTo!element],
	NULL AS [Remittance!7!TotalValue!element],
	NULL AS [Remittance!7!VAT!element],
	NULL AS [Remittance!7!NetValue!element],
	rd.[ID] AS [RemittanceLine!8!ID],
	rd.Type AS [RemittanceLine!8!Type],
	'<![CDATA[' + CONVERT(VARCHAR(8000), rd.Comment) + ']]>' AS [RemittanceLine!8!Comment!xml],
	rd.PeriodFrom AS [RemittanceLine!8!DateFrom!element],
	rd.PeriodTo AS [RemittanceLine!8!DateTo!element],
	rd.LineValue AS [RemittanceLine!8!Value!element],
	rd.LineVAT AS [RemittanceLine!8!VAT!element],
	(rd.LineValue - rd.LineVAT) AS [RemittanceLine!8!NetValue!element],
	'<![CDATA[' + rd.LineReference + ']]>' AS [RemittanceLine!8!Reference!xml]
FROM SPRemittanceDetail AS rd
	INNER JOIN SPRemittance AS r ON (r.[ID] = rd.RemittanceID)
	INNER JOIN SPSubsidyAgreement AS sub ON (sub.[ID] = rd.RelatedID)
	INNER JOIN SPServiceAgreement AS sa ON (sa.[ID] = sub.ServiceAgreementID)
	INNER JOIN User_SPService AS us ON (us.SPServiceID = sa.ServiceID)
	INNER JOIN SPContractHeader AS ch ON (ch.[ID] = r.ContractID)
	LEFT OUTER JOIN SPContractRate AS cr ON (cr.[ID] = rd.ContractRateID)
WHERE r.InterfaceLogID IS NOT NULL
AND (@intServiceID IS NULL OR (@intServiceID IS NOT NULL AND sa.ServiceID = @intServiceID))
AND us.UserID = @intUserID
AND sa.ClientID = @intClientID
AND (@dteDateFrom IS NULL OR (@dteDateFrom IS NOT NULL AND DATEDIFF(dd, @dteDateFrom, r.DateTo) >= 0))
AND (@dteDateTo IS NULL OR (@dteDateTo IS NOT NULL AND DATEDIFF(dd, @dteDateTo, r.DateFrom) <= 0))

ORDER BY [Remittance!7!ID], tag, [ServiceAgreement!6!DateFrom!element] DESC, [RemittanceLine!8!ID]

FOR XML EXPLICIT


GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

