if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[WebSPSUNotif]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
drop table [dbo].[WebSPSUNotif]
GO

CREATE TABLE [dbo].[WebSPSUNotif] (
	[ID] [int] IDENTITY (1, 1) NOT NULL ,
	[TypeID] [tinyint] NOT NULL ,
	[StatusID] [tinyint] NOT NULL ,
	[CreatedDate] [datetime] NOT NULL ,
	[SubmittedDate] [datetime] NULL ,
	[CompletedDate] [datetime] NULL ,
	[RequestedByUserID] [int] NOT NULL ,
	[SPProviderID] [int] NULL ,
	[SPServiceID] [int] NULL ,
	[ServiceStartDate] [datetime] NULL ,
	[TenancyServiceAgreement] [bit] NULL ,
	[PrimaryTitleID] [int] NULL ,
	[PrimaryFirstNames] [varchar] (20) NULL ,
	[PrimaryLastName] [varchar] (20) NULL ,
	[PrimaryNINo] [varchar] (9) NULL ,
	[PrimaryBirthDate] [datetime] NULL ,
	[SecondaryTitleID] [int] NULL ,
	[SecondaryFirstNames] [varchar] (20) NULL ,
	[SecondaryLastName] [varchar] (20) NULL ,
	[SecondaryNINo] [varchar] (9) NULL ,
	[SecondaryBirthDate] [datetime] NULL ,
	[Address] [text] NULL ,
	[Postcode] [varchar] (10) NULL ,
	[WebFileStoreDataID] [int] NULL ,
	[SPSubsidyAgreementID] [int] NULL ,
	[SubsidyEndDate] [datetime] NULL ,
	[Comment] [text] NULL ,
	[ProcessedByUserID] [int] NULL ,
	[SubsidyEndReasonID] [int] NULL ,
	[YourReference] [varchar] (25) NULL ,
	[ServiceLevel] [varchar] (25) NULL ,
	[UnitCost] [money] NULL 
) ON [TARGET_WEB] TEXTIMAGE_ON [TARGET_WEB]
GO

ALTER TABLE [dbo].[WebSPSUNotif] WITH NOCHECK ADD 
	CONSTRAINT [PK_WebSPSUNotif] PRIMARY KEY  CLUSTERED 
	(
		[ID]
	)  ON [TARGET_WEB] 
GO

ALTER TABLE [dbo].[WebSPSUNotif] ADD 
	CONSTRAINT [FK_WebSPSUNotif_SPProvider] FOREIGN KEY 
	(
		[SPProviderID]
	) REFERENCES [dbo].[SPProvider] (
		[ID]
	),
	CONSTRAINT [FK_WebSPSUNotif_SPService] FOREIGN KEY 
	(
		[SPServiceID]
	) REFERENCES [dbo].[SPService] (
		[ID]
	),
	CONSTRAINT [FK_WebSPSUNotif_SPSubsidyAgreement1] FOREIGN KEY 
	(
		[SPSubsidyAgreementID]
	) REFERENCES [dbo].[SPSubsidyAgreement] (
		[ID]
	),
	CONSTRAINT [FK_WebSPSUNotif_SPSubsidyEndReason] FOREIGN KEY 
	(
		[SubsidyEndReasonID]
	) REFERENCES [dbo].[SPSubsidyEndReason] (
		[ID]
	),
	CONSTRAINT [FK_WebSPSUNotif_WebFileStoreData] FOREIGN KEY 
	(
		[WebFileStoreDataID]
	) REFERENCES [dbo].[WebFileStoreData] (
		[ID]
	),
	CONSTRAINT [FK_WebSPSUNotif_WebSecurityUser] FOREIGN KEY 
	(
		[RequestedByUserID]
	) REFERENCES [dbo].[WebSecurityUser] (
		[ID]
	),
	CONSTRAINT [FK_WebSPSUNotif_WebSecurityUser1] FOREIGN KEY 
	(
		[ProcessedByUserID]
	) REFERENCES [dbo].[WebSecurityUser] (
		[ID]
	)
GO





/****** Object:  Stored Procedure [dbo].spxWebSPSUNotif_Fetch    Script Date: 05 March 2007 ******/
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[spxWebSPSUNotif_Fetch]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[spxWebSPSUNotif_Fetch]
GO


/****** Object:  Stored Procedure [dbo].spxWebSPSUNotif_Save    Script Date: 05 March 2007 ******/
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[spxWebSPSUNotif_Save]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[spxWebSPSUNotif_Save]
GO

/****** Object:  Stored Procedure [dbo].spxWebSPSUNotif_Delete    Script Date: 05 March 2007 ******/
if exists (select * from dbo.sysobjects where id = object_id(N'[dbo].[spxWebSPSUNotif_Delete]') and OBJECTPROPERTY(id, N'IsProcedure') = 1)
drop procedure [dbo].[spxWebSPSUNotif_Delete]
GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS OFF 
GO
------------------------------------------------------------------------------------------------------------------------
-- Date Created: 05/03/2007 12:06:55
-- Created By:   Generated by CodeSmith
-- Do not modify this code manually as it will be overwritten the next time the code is generated.
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spxWebSPSUNotif_Fetch]
	@ID int
AS

SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[ID],
	[TypeID],
	[StatusID],
	[CreatedDate],
	[SubmittedDate],
	[CompletedDate],
	[RequestedByUserID],
	[SPProviderID],
	[SPServiceID],
	[ServiceStartDate],
	[TenancyServiceAgreement],
	[PrimaryTitleID],
	[PrimaryFirstNames],
	[PrimaryLastName],
	[PrimaryNINo],
	[PrimaryBirthDate],
	[SecondaryTitleID],
	[SecondaryFirstNames],
	[SecondaryLastName],
	[SecondaryNINo],
	[SecondaryBirthDate],
	[Address],
	[Postcode],
	[WebFileStoreDataID],
	[SPSubsidyAgreementID],
	[SubsidyEndDate],
	[Comment],
	[ProcessedByUserID],
	[SubsidyEndReasonID],
	[YourReference],
	[ServiceLevel],
	[UnitCost]
FROM
	[dbo].[WebSPSUNotif]
WHERE
	[dbo].[WebSPSUNotif].[ID] = @ID
GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT EXECUTE ON [dbo].[spxWebSPSUNotif_Fetch] TO [public]
GO


SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO
------------------------------------------------------------------------------------------------------------------------
-- Date Created: 05/03/2007 12:06:55
-- Created By:   Generated by CodeSmith
-- Do not modify this code manually as it will be overwritten the next time the code is generated.
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spxWebSPSUNotif_Save]
	@ID int = NULL OUTPUT,
	@TypeID tinyint,
	@StatusID tinyint,
	@CreatedDate datetime,
	@SubmittedDate datetime,
	@CompletedDate datetime,
	@RequestedByUserID int,
	@SPProviderID int = NULL,
	@SPServiceID int = NULL,
	@ServiceStartDate datetime,
	@TenancyServiceAgreement bit,
	@PrimaryTitleID int = NULL,
	@PrimaryFirstNames varchar(20),
	@PrimaryLastName varchar(20),
	@PrimaryNINo varchar(9),
	@PrimaryBirthDate datetime,
	@SecondaryTitleID int = NULL,
	@SecondaryFirstNames varchar(20),
	@SecondaryLastName varchar(20),
	@SecondaryNINo varchar(9),
	@SecondaryBirthDate datetime,
	@Address text,
	@Postcode varchar(10),
	@WebFileStoreDataID int = NULL,
	@SPSubsidyAgreementID int = NULL,
	@SubsidyEndDate datetime,
	@Comment text,
	@ProcessedByUserID int = NULL,
	@SubsidyEndReasonID int = NULL,
	@YourReference varchar(25),
	@ServiceLevel varchar(25),
	@UnitCost money
AS

IF @ID IS NULL 

BEGIN
	INSERT INTO [dbo].[WebSPSUNotif] (
		[TypeID],
		[StatusID],
		[CreatedDate],
		[SubmittedDate],
		[CompletedDate],
		[RequestedByUserID],
		[SPProviderID],
		[SPServiceID],
		[ServiceStartDate],
		[TenancyServiceAgreement],
		[PrimaryTitleID],
		[PrimaryFirstNames],
		[PrimaryLastName],
		[PrimaryNINo],
		[PrimaryBirthDate],
		[SecondaryTitleID],
		[SecondaryFirstNames],
		[SecondaryLastName],
		[SecondaryNINo],
		[SecondaryBirthDate],
		[Address],
		[Postcode],
		[WebFileStoreDataID],
		[SPSubsidyAgreementID],
		[SubsidyEndDate],
		[Comment],
		[ProcessedByUserID],
		[SubsidyEndReasonID],
		[YourReference],
		[ServiceLevel],
		[UnitCost]
	) VALUES (
		@TypeID,
		@StatusID,
		@CreatedDate,
		@SubmittedDate,
		@CompletedDate,
		@RequestedByUserID,
		@SPProviderID,
		@SPServiceID,
		@ServiceStartDate,
		@TenancyServiceAgreement,
		@PrimaryTitleID,
		@PrimaryFirstNames,
		@PrimaryLastName,
		@PrimaryNINo,
		@PrimaryBirthDate,
		@SecondaryTitleID,
		@SecondaryFirstNames,
		@SecondaryLastName,
		@SecondaryNINo,
		@SecondaryBirthDate,
		@Address,
		@Postcode,
		@WebFileStoreDataID,
		@SPSubsidyAgreementID,
		@SubsidyEndDate,
		@Comment,
		@ProcessedByUserID,
		@SubsidyEndReasonID,
		@YourReference,
		@ServiceLevel,
		@UnitCost
	)
	
	SET @ID = @@IDENTITY
END
ELSE
BEGIN
	UPDATE [dbo].[WebSPSUNotif] SET
		[TypeID] = @TypeID,
		[StatusID] = @StatusID,
		[CreatedDate] = @CreatedDate,
		[SubmittedDate] = @SubmittedDate,
		[CompletedDate] = @CompletedDate,
		[RequestedByUserID] = @RequestedByUserID,
		[SPProviderID] = @SPProviderID,
		[SPServiceID] = @SPServiceID,
		[ServiceStartDate] = @ServiceStartDate,
		[TenancyServiceAgreement] = @TenancyServiceAgreement,
		[PrimaryTitleID] = @PrimaryTitleID,
		[PrimaryFirstNames] = @PrimaryFirstNames,
		[PrimaryLastName] = @PrimaryLastName,
		[PrimaryNINo] = @PrimaryNINo,
		[PrimaryBirthDate] = @PrimaryBirthDate,
		[SecondaryTitleID] = @SecondaryTitleID,
		[SecondaryFirstNames] = @SecondaryFirstNames,
		[SecondaryLastName] = @SecondaryLastName,
		[SecondaryNINo] = @SecondaryNINo,
		[SecondaryBirthDate] = @SecondaryBirthDate,
		[Address] = @Address,
		[Postcode] = @Postcode,
		[WebFileStoreDataID] = @WebFileStoreDataID,
		[SPSubsidyAgreementID] = @SPSubsidyAgreementID,
		[SubsidyEndDate] = @SubsidyEndDate,
		[Comment] = @Comment,
		[ProcessedByUserID] = @ProcessedByUserID,
		[SubsidyEndReasonID] = @SubsidyEndReasonID,
		[YourReference] = @YourReference,
		[ServiceLevel] = @ServiceLevel,
		[UnitCost] = @UnitCost
	WHERE
		[ID] = @ID
END
GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT EXECUTE ON [dbo].[spxWebSPSUNotif_Save] TO [public]
GO


SET QUOTED_IDENTIFIER ON 
GO
SET ANSI_NULLS OFF 
GO
------------------------------------------------------------------------------------------------------------------------
-- Date Created: 05/03/2007 12:06:55
-- Created By:   Generated by CodeSmith
-- Do not modify this code manually as it will be overwritten the next time the code is generated.
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[spxWebSPSUNotif_Delete]
	@strError varchar(1000) = '' OUTPUT,
	@ID int
AS

DECLARE @intCount int

IF LEN(@strError) = 0
BEGIN
	DELETE FROM [dbo].[WebSPSUNotif]
	WHERE
		[dbo].[WebSPSUNotif].[ID] = @ID
END

GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

GRANT EXECUTE ON [dbo].[spxWebSPSUNotif_Delete] TO [public]
GO


