'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.General.DebtorInvoices

    Partial Public Class PrintInvoice

        '''<summary>
        '''lblFilterDebtor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilterDebtor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFilterInvTypes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilterInvTypes As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFilterCreationDates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilterCreationDates As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFilterOther control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilterOther As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilter As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblFilters control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFilters As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rptInvoices control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rptInvoices As Global.System.Web.UI.WebControls.Repeater
    End Class
End Namespace
