'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1873
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.General.DebtorInvoices

    Partial Public Class RecreateBatchFiles

        '''<summary>
        '''lblCreatedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreatedDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCreatedBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreatedBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvoiceCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvoiceCount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvoiceValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvoiceValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPostingDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPostingDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPostingYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPostingYear As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblPeriodNum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPeriodNum As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grpRecreateInterface control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grpRecreateInterface As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''chkRereadData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkRereadData As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblRereadData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRereadData As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkCustomerFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCustomerFile As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblCustomerFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCustomerFile As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''optCreateNow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optCreateNow As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''optDefer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optDefer As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''dteStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dteStartDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''tmeStartDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tmeStartDate As Global.Target.Library.Web.Controls.TimePicker

        '''<summary>
        '''dtePostingDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dtePostingDate As Global.Target.Library.Web.Controls.TextBoxEx

        '''<summary>
        '''cboPostingYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboPostingYear As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''cboPeriodNum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboPeriodNum As Global.Target.Library.Web.Controls.DropDownListEx

        '''<summary>
        '''btnRecreate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnRecreate As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
