'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Apps.General.DebtorInvoices

    Partial Public Class ViewBatchInvoices

        '''<summary>
        '''lblCreatedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreatedDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCreatedBy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCreatedBy As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvoiceCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvoiceCount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblInvoiceValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvoiceValue As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
